/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-21 08:17:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class postDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1638513134000L));
    _jspx_dependants.put("jar:file:/D:/workspace_photofolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/photofolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시글상세조회</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"http://example.com/myicon.png\"> \r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\" integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $(\"#header\").load(\"/resources/header/header.jsp\")      \r\n");
      out.write("         });\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("*{box-sizing: border-box;\r\n");
      out.write("    margin:0;}\r\n");
      out.write("\r\n");
      out.write("/* 게시글 전체 컨테이너 */\r\n");
      out.write(".postDetailContainer{\r\n");
      out.write("	border:1px solid lightgray;\r\n");
      out.write("	width:1200px;\r\n");
      out.write("	height:auto;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*댓글 전체 컨테이너 */\r\n");
      out.write(".commentContainer{\r\n");
      out.write("	border:1px solid lightgray;\r\n");
      out.write("	width:1200px;\r\n");
      out.write("	height:auto;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*============================게시글 제목====================================*/\r\n");
      out.write("\r\n");
      out.write(".post_title{\r\n");
      out.write("	border-bottom:double;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:100px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("#btnReport{\r\n");
      out.write("	width:80px;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("#followBtn, #followingBtn{\r\n");
      out.write("	width:100px;\r\n");
      out.write("	background-color:rgb(86, 86, 196);\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("/*========================================================================*/\r\n");
      out.write("/*===================게시글 메인=========================================*/\r\n");
      out.write(".post_main{\r\n");
      out.write("	\r\n");
      out.write("	width:100%;\r\n");
      out.write("	height:auto;\r\n");
      out.write("}\r\n");
      out.write("#post_title{\r\n");
      out.write("	border:none;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	font-family: 'Jua', sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".uploadBox{\r\n");
      out.write("	width:1000px;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	display:none; /*수정버튼 클릭시 보이게할것*/\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".photoBox{\r\n");
      out.write("	width:1000px;\r\n");
      out.write("	height:auto;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("}\r\n");
      out.write(".contentBox{\r\n");
      out.write("	width:1000px;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	height:auto;\r\n");
      out.write("	border:1px solid lightgray;\r\n");
      out.write("}\r\n");
      out.write(".contentBox>textarea{\r\n");
      out.write(" 	min-height: 5rem;\r\n");
      out.write("	resize:none;\r\n");
      out.write("	border:none;\r\n");
      out.write("	overflow-y: hidden;\r\n");
      out.write("	font-family: 'Jua', sans-serif;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnBox{\r\n");
      out.write("	text-align:right;\r\n");
      out.write("	margin-right:10px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".btnBox>div>button{\r\n");
      out.write("	background-color:rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write("#btnsBox{\r\n");
      out.write("	display:block; /*자기게시글일 경우만 display:block 해줄것*/\r\n");
      out.write("}\r\n");
      out.write("#btnModifyDetailBox{\r\n");
      out.write("	display:none; /*수정버튼 누를때만 display:block 해줄것*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#beforeGoodBtnBox{\r\n");
      out.write("	display:block; /*초기화면이면 block */\r\n");
      out.write("}\r\n");
      out.write("#afterGoodBtnBox{\r\n");
      out.write("	display:none; /*초기화면이면 none*/\r\n");
      out.write("}\r\n");
      out.write("#beforeGoodBtn{\r\n");
      out.write("	color:white;\r\n");
      out.write("	border:1px solid rgb(86, 86, 196);\r\n");
      out.write("	background-color:rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#afterGoodBtn{\r\n");
      out.write("	color:white;\r\n");
      out.write("	background-color:rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write("/*따봉 색깔 논의 필요*/\r\n");
      out.write("#afterGoodBtn>svg{\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*==================================================================*/\r\n");
      out.write("/*===========================댓글 영역 ==============================*/\r\n");
      out.write(".commentTitle{\r\n");
      out.write("	border-bottom: 1px double gray;\r\n");
      out.write("}\r\n");
      out.write(".cmt-showBox{\r\n");
      out.write("	margin-left:30px;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".cmt-showBox>div{\r\n");
      out.write("	height:50px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".cmtReport{\r\n");
      out.write("	padding:2px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("#comment_content{\r\n");
      out.write("	resize:none;\r\n");
      out.write("	border:none;\r\n");
      out.write("	width:400px;\r\n");
      out.write("	overflow:visible;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#btnReModify, #btnReDelete, #btnReBack {\r\n");
      out.write("	background-color: rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write("#btnReDelete{\r\n");
      out.write("	background-color: rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write("#beforeReBtnBox{\r\n");
      out.write("	display:block; /*수정버튼 누르면 none*/\r\n");
      out.write("	text-align:right;\r\n");
      out.write("	width:100%;\r\n");
      out.write("}\r\n");
      out.write(".btnBox{\r\n");
      out.write("	height:40px;\r\n");
      out.write("}\r\n");
      out.write("#afterReBtnBox{\r\n");
      out.write("	display:none; /*수정버튼 누르면 block*/\r\n");
      out.write("	text-align:right;\r\n");
      out.write("	width:100%;\r\n");
      out.write("	padding-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".commentInput{\r\n");
      out.write("	border:1px solid gray;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	width:1100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content-cmt{\r\n");
      out.write("	width:900px;\r\n");
      out.write("	min-height: 5rem;\r\n");
      out.write("	resize:none;\r\n");
      out.write("	overflow-y: hidden;\r\n");
      out.write("}\r\n");
      out.write("#modi_content_cmt{\r\n");
      out.write("	width:900px;\r\n");
      out.write("	min-height: 5rem;\r\n");
      out.write("	resize:none;\r\n");
      out.write("}\r\n");
      out.write("#btnReInsert{\r\n");
      out.write("	width:100px;\r\n");
      out.write("	height:80px;\r\n");
      out.write("	margin-left:40px;\r\n");
      out.write("	background-color:rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write(".cmtReport{\r\n");
      out.write("	margin-bottom:65px;\r\n");
      out.write("}\r\n");
      out.write(".modiBox{\r\n");
      out.write("	border:1px solid gray;\r\n");
      out.write("	margin:auto;\r\n");
      out.write("	width:1100px;\r\n");
      out.write("	margin-right:80px;\r\n");
      out.write("}\r\n");
      out.write("#btnReGo{\r\n");
      out.write("	width:100px;\r\n");
      out.write("	height:80px;\r\n");
      out.write("	margin-left:40px;\r\n");
      out.write("	background-color:rgb(86, 86, 196);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"Wrapper\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- 헤더쪽(링크로 불러옴) -->\r\n");
      out.write("		<div id=\"header\"></div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 게시글쪽 -->\r\n");
      out.write("		<div class=\"postDetailContainer mt-5 mb-5\">\r\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/modifyProc.bo\" method=\"post\" id=\"modifyPost\"\r\n");
      out.write("			enctype=\"multipart/form-data\">\r\n");
      out.write("               <!-- 게시글 제목단 -->\r\n");
      out.write("            	<div class=\"post_title\">\r\n");
      out.write("            		<!-- 게시글제목+신고버튼 함께 담을 공간 -->\r\n");
      out.write("            		<div class=\"row mt-2 mx-1\" id=\"post_title_head\">\r\n");
      out.write("            			<!-- 게시글 제목 -->\r\n");
      out.write("            			<input type=\"text\" class=\"\" id=\"post_no\" name=\"post_no\"\r\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("            			<div class=\"col-11\" id=\"title\">\r\n");
      out.write("            				<h2>\r\n");
      out.write("            				<input type=\"text\" id=\"post_title\" name=\"post_title\"\r\n");
      out.write("								value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_title() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly> \r\n");
      out.write("            				</h2>\r\n");
      out.write("            			</div>\r\n");
      out.write("            			<!-- 신고버튼(자기게시글에는 신고X) -->\r\n");
      out.write("            			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<!-- 사용자,등록일,조회수, 팔로우버튼 담을 공간 -->\r\n");
      out.write("            		<div class=\"row mx-4\" id=\"post_title_main\">\r\n");
      out.write("            			<!-- 사용자, 등록일, 조회수 -->\r\n");
      out.write("            			<div class=\"col-11 mt-2\">\r\n");
      out.write("            				<span>by ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_writer_nickname() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" || ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_createdDate() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" || 조회수 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_view_count() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("            			</div>\r\n");
      out.write("            			<!-- 팔로우 버튼 -->\r\n");
      out.write("            			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            		</div>\r\n");
      out.write("            	</div>	\r\n");
      out.write("            	\r\n");
      out.write("            	 \r\n");
      out.write("            	<!-- 게시글사진 + 게시글내용 + 수정삭제버튼 담을 곳 -->\r\n");
      out.write("            	<div class=\"post_main\">\r\n");
      out.write("            		<!-- 수정시 사진파일 업로드시킬 인풋창 -->\r\n");
      out.write("					<div class=\"mt-4 uploadBox\">\r\n");
      out.write("						<input class=\"form-control form-control-sm\" id=\"formFileSm\"\r\n");
      out.write("							name=\"photo_path\" type=\"file\" accept=\"image/*\"\r\n");
      out.write("							onchange=\"readImg(event)\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 게시글 사진 불러올 공간 -->\r\n");
      out.write("            		<div class=\"row my-4 photoBox\">\r\n");
      out.write("            			<img id=\"post_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/files/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dtoFile.getSystem_name()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<!-- 사진 미리 보기 -->\r\n");
      out.write("					<div class=\"row my-4 photoBox\" id=\"preview\"></div>\r\n");
      out.write("            		<!-- 게시글 내용 불러올 공간 -->\r\n");
      out.write("            		<div class=\"row contentBox\">\r\n");
      out.write("            			<textarea id=\"post_content\" onkeydown=\"resize(this)\" onkeyup=\"resize(this)\"\r\n");
      out.write("							name=\"post_content\" readonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_content() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("            		</div>\r\n");
      out.write("            		<!-- 수정,삭제 버튼 공간(다른사용자 게시글일 경우 hidden) -->\r\n");
      out.write("            		");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            		<!-- 종아요 버튼 -->\r\n");
      out.write("            		<!-- 버튼 누르기전 좋아요 -->\r\n");
      out.write("            		");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            		\r\n");
      out.write("            	</div>  	\r\n");
      out.write("            </form>\r\n");
      out.write("        </div><!-- 게시글 div끝  -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- 댓글부분 -->\r\n");
      out.write("	       <div class=\"commentContainer\">\r\n");
      out.write("	       		<!-- 댓글 제목 -->\r\n");
      out.write("	       			<div class=\"row mx-2 my-2 commentTitle\">\r\n");
      out.write("	       				<div class=\"col\">\r\n");
      out.write("	       				   <h2>\r\n");
      out.write("	       				   	   <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\"\r\n");
      out.write("	                              fill=\"currentColor\" class=\"bi bi-chat-dots\" viewBox=\"0 0 16 16\">\r\n");
      out.write("	                                <path\r\n");
      out.write("	                                d=\"M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z\" />\r\n");
      out.write("	                                <path\r\n");
      out.write("	                                d=\"m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z\" />\r\n");
      out.write("	                            </svg>\r\n");
      out.write("	                            <span>Reply</span>\r\n");
      out.write("	       				   </h2>\r\n");
      out.write("	       				</div>\r\n");
      out.write("	       			</div>\r\n");
      out.write("	       			<!-- 댓글 내용부분 -->\r\n");
      out.write("	       			<div class=\"row commentMain\">\r\n");
      out.write("	       				<!-- 댓글(1파트) -->\r\n");
      out.write("	       				\r\n");
      out.write("		                   <div class=\"cmt-showBox\"></div>\r\n");
      out.write("		                \r\n");
      out.write("		                <!-- 댓글입력부분 -->\r\n");
      out.write("		                <div class=\"commentInput\">\r\n");
      out.write("		                <form method=\"post\" id=\"cmtForm\">\r\n");
      out.write("		                	<div class=\"row mx-2 mb-2 mt-2\">\r\n");
      out.write("		                		<div class=\"col\">\r\n");
      out.write("		                			<label>댓글쓰기</label>\r\n");
      out.write("		                		</div>\r\n");
      out.write("		                	</div>\r\n");
      out.write("		                	<div class=\"row mx-2  comment-body\">\r\n");
      out.write("		                		<div class=\"col-10 comment-input\">\r\n");
      out.write("		                			<textarea id=\"content-cmt\" name=\"comment_content\" onkeydown='resize(this)' onkeyup='resize(this)'></textarea>\r\n");
      out.write("		                		</div>\r\n");
      out.write("		                		<div class=\"col-2 comment-input\">\r\n");
      out.write("		                			<button type=\"button\" id=\"btnReInsert\" class=\"btn btn-dark\">등록</button>\r\n");
      out.write("		                		</div>\r\n");
      out.write("		                		<input type=\"text\" name=\"currentPage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("								<input type=\"text\" name=\"post_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("								<input type=\"text\" name=\"comment_writer_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_writer()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("		                	</div>	\r\n");
      out.write("		                	</form>\r\n");
      out.write("		                </div>\r\n");
      out.write("	       </div><!-- 댓글 div끝 -->  \r\n");
      out.write("	</div><!-- 전체 div 끝 -->\r\n");
      out.write("	\r\n");
      out.write("	 <script src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("      integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("      \r\n");
      out.write("	<script>\r\n");
      out.write("	//텍스트창 자동 길이늘림\r\n");
      out.write("	function resize(obj) {\r\n");
      out.write("	    obj.style.height = '1px';\r\n");
      out.write("	    obj.style.height = (12 + obj.scrollHeight) + 'px';\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//좋아요 버튼 변동\r\n");
      out.write("	//좋아요 기록할 경우 \r\n");
      out.write("	$(\"#beforeGoodBtn\").click(function(){\r\n");
      out.write("		$(\"#beforeGoodBtnBox\").css(\"display\",\"none\");\r\n");
      out.write("		$(\"#afterGoodBtnBox\").css(\"display\",\"block\");\r\n");
      out.write("	})\r\n");
      out.write("	//좋아요 해제할 경우\r\n");
      out.write("	$(\"#afterGoodBtn\").click(function(){\r\n");
      out.write("		$(\"#beforeGoodBtnBox\").css(\"display\",\"block\");\r\n");
      out.write("		$(\"#afterGoodBtnBox\").css(\"display\",\"none\");\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//게시글 수정버튼 누를경우 처리\r\n");
      out.write("	$(\"#btnModify\").click(function(){\r\n");
      out.write("		$(\"#btnsBox\").css(\"display\",\"none\");\r\n");
      out.write("		$(\"#btnModifyDetailBox\").css(\"display\",\"block\");\r\n");
      out.write("		$(\".uploadBox\").css(\"display\", \"block\");\r\n");
      out.write("		$(\"#post_title\").attr(\"readonly\", false);\r\n");
      out.write("		$(\"#post_content\").attr(\"readonly\", false);\r\n");
      out.write("		$(\"#post_title\").css(\"border\",\"1px solid black\");\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	// 수정 이미지 미리 보기\r\n");
      out.write("    	function readImg(event) {\r\n");
      out.write("    		let reader = new FileReader();\r\n");
      out.write("    		reader.onload = function(e) {\r\n");
      out.write("    			$(\"#post_img\").remove();\r\n");
      out.write("    			let img = document.createElement(\"img\");\r\n");
      out.write("    			img.setAttribute(\"src\", e.target.result);\r\n");
      out.write("    			document.querySelector(\"div#preview\").appendChild(img);\r\n");
      out.write("    		};\r\n");
      out.write("    		reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("    	}\r\n");
      out.write("	\r\n");
      out.write("    // 이미지 미리보기 할때 사진 변환\r\n");
      out.write("    function readInputFile(e){\r\n");
      out.write("        let sel_files = [];\r\n");
      out.write("        \r\n");
      out.write("        sel_files = [];\r\n");
      out.write("        $('#preview').empty();\r\n");
      out.write("        \r\n");
      out.write("        let files = e.target.files;\r\n");
      out.write("        let fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("        let index = 0;\r\n");
      out.write("        \r\n");
      out.write("        fileArr.forEach(function(f){\r\n");
      out.write("        	 if(!f.type.match(\"image/*\")){\r\n");
      out.write("                 alert(\"이미지 확장자만 업로드 가능합니다.\");\r\n");
      out.write("                  return;\r\n");
      out.write("              };\r\n");
      out.write("\r\n");
      out.write("            if(files.length > 2){\r\n");
      out.write("               sel_files.push(f);\r\n");
      out.write("               console.log(f.type);\r\n");
      out.write("                let reader = new FileReader();\r\n");
      out.write("                reader.onload = function(e){\r\n");
      out.write("                   let html = `<a id=img_id_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("><img src=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${e.target.result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" data-file=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" /></a>`;\r\n");
      out.write("                    $(\"#preiew\").append(html);\r\n");
      out.write("                    index++;\r\n");
      out.write("                    alert(\"사진은 1장만 등록 할 수 있습니다.\");\r\n");
      out.write("                };\r\n");
      out.write("                reader.readAsDataURL(f);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    }\r\n");
      out.write("    $('#formFileSm').on('change',readInputFile);\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    // 수정 확인 버튼 처리 \r\n");
      out.write("    $(\"#btnGo\").on(\"click\", function(){\r\n");
      out.write("       let photo_path = document.getElementById(\"formFileSm\");\r\n");
      out.write("       let post_title = document.getElementById(\"post_title\")\r\n");
      out.write("       let post_content = document.getElementById(\"post_content\");\r\n");
      out.write("       let fileType = /(.*?)\\.(jpg|jpeg|png|gif|bmp|pdf)$/;\r\n");
      out.write("       let imgFile = $('#formFileSm').val();\r\n");
      out.write("       \r\n");
      out.write("        if(post_title.value == \"\") {\r\n");
      out.write("             alert(\"제목을 입력 해주세요.\");\r\n");
      out.write("             return;\r\n");
      out.write("        }else if (post_content.value == \"\") {\r\n");
      out.write("             alert(\"내용을 입력 해주세요.\");\r\n");
      out.write("             return;\r\n");
      out.write("          }\r\n");
      out.write("          $(\"#modifyPost\").submit();\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	// 게시물 삭제 버튼\r\n");
      out.write("	$(\"#btnDelete\").on(\"click\", function(){\r\n");
      out.write("		confirm(\"삭제 하시겠습니까?\");\r\n");
      out.write("		location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteProc.bo?post_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	//뒤로돌아가기\r\n");
      out.write("	$(\"#btnBack\").click(function(){\r\n");
      out.write("		location.reload();\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		// 댓글 영역\r\n");
      out.write("	\r\n");
      out.write("		// 페이지 로드되자마자 댓글도 ajax 로 로드\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			getCommentList();\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		// 댓글 등록\r\n");
      out.write("		$(\"#btnReInsert\").on(\"click\", function(){\r\n");
      out.write("			let data = $(\"#cmtForm\").serialize(); // 댓글 form 안의 데이터 직렬화\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			$(\"#content-cmt\").val(\"\");\r\n");
      out.write("			if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginSession}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					// aJax 댓글 추가\r\n");
      out.write("					url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/insertProc.co\"\r\n");
      out.write("					, type : \"post\"\r\n");
      out.write("					, data : data				\r\n");
      out.write("				}).done(function(rs){\r\n");
      out.write("					if(rs == \"success\"){\r\n");
      out.write("						getCommentList();// 댓글 동록에 성공하면 댓글 리스트 리로드\r\n");
      out.write("					}else if(rs == \"fail\"){\r\n");
      out.write("						alert(\"댓글 등록에 실패했습니다.\"); // 댓글 등록에 실패하면 alert \r\n");
      out.write("					}				\r\n");
      out.write("				}).fail(function(e){\r\n");
      out.write("					console.log(e);\r\n");
      out.write("				});\r\n");
      out.write("			}else{\r\n");
      out.write("				alert(\"로그인을 하고 서비스를 이용해 주세요.\");\r\n");
      out.write("				location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.jsp\"\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});		\r\n");
      out.write("	\r\n");
      out.write("		// ajax를 이용해 댓글을 불러오는 함수\r\n");
      out.write("		function getCommentList(){		\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"get\"\r\n");
      out.write("				,async:false\r\n");
      out.write("				, url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getCommentProc.co?post_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				, dataType : \"json\"\r\n");
      out.write("			}).done(function(data){\r\n");
      out.write("				if(!(data==\"fail\")){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				$(\".cmt-showBox\").empty();\r\n");
      out.write("				for(let cmt_dto of data){\r\n");
      out.write("							let comment = \r\n");
      out.write("						     \"<div class='row mb-2 mx-1 my-3'>\"\r\n");
      out.write("							+ \"<div class='col-6 tempBox'>\"\r\n");
      out.write("							+ \"<div value='\" + cmt_dto.comment_no + \"' id='comment_content' name='comment_content'>\" + cmt_dto.content + \"</div>\"	\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+ \"<div class='col-3'>\"\r\n");
      out.write("							+ cmt_dto.user_nickname +  \"|\" +cmt_dto.createdDate\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+ \"<div class='col-2 btnBox'>\"\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+\"<form method='post' id='modiCmtForm'>\"\r\n");
      out.write("							+ \"<div class='modiBox' id='modiBox' value='\" + cmt_dto.comment_no + \"' hidden>\"\r\n");
      out.write("							+\"<div class='row mx-2 mb-2 mt-2'>\"\r\n");
      out.write("							+\"<div class='col'>\"\r\n");
      out.write("                			+\"<label>댓글수정</label>\"\r\n");
      out.write("	                		+\"</div>\"\r\n");
      out.write("	                		+\"<div class='row mx-2  comment-body'>\"\r\n");
      out.write("							+\"<div class='col-10 comment-input'>\"\r\n");
      out.write("							+\"<textarea id='modi_content_cmt' class='modi_content_cmt' name='\" +cmt_dto.comment_no+ \"' onkeydown='resize(this)' onkeyup='resize(this)'>\"+cmt_dto.content +\"</textarea>\"\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+\"<div class='col-2 comment-input'>\"\r\n");
      out.write("							+\"<button type='button' id='btnReGo'  value='\" + cmt_dto.comment_no + \"' class='btn btn-dark btnReGo'>등록</button>\"\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+\"</form>\"\r\n");
      out.write("						\r\n");
      out.write("							$(\".cmt-showBox\").append(comment);\r\n");
      out.write("							\r\n");
      out.write("							let btn=\"\"\r\n");
      out.write("							\r\n");
      out.write("							if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get('user_id')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == cmt_dto.user_id){\r\n");
      out.write("										let btns=\"<div class='col-3' class='reBtnBox' id='beforeReBtnBox'>\"\r\n");
      out.write("										+\" <button type='button' id='btnReModify' value='\" +cmt_dto.comment_no + \"' class='btn btn-dark btn-sm btnReModify'>수정</button>\"\r\n");
      out.write("										+ \"<button type='button' id='btnReDelete' value='\" + cmt_dto.comment_no + \"' class='btn btn-dark btn-sm'>삭제</button>\"\r\n");
      out.write("										+\"</div>\"\r\n");
      out.write("										+\"<div class='col-3' class='reBtnBox' id='afterReBtnBox'>\"\r\n");
      out.write("										+\"<button type='button' id='btnReBack' class='btn btn-dark btn-sm'>취소</button>\"\r\n");
      out.write("										+\"</div>\"\r\n");
      out.write("\r\n");
      out.write("										$(\".btnBox:last\").append(btns);\r\n");
      out.write("							\r\n");
      out.write("										\r\n");
      out.write("									}\r\n");
      out.write("							//자기게시글에는 신고X\r\n");
      out.write("							if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get('user_id')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" != cmt_dto.user_id){\r\n");
      out.write("								\r\n");
      out.write("								let report =  \"<button tpye='button' id = 'cmtReport' value='\" + cmt_dto.comment_no + \"' class='btn btn-danger btn-sm cmtReport'>신고</button>\"\r\n");
      out.write("								\r\n");
      out.write("								$(\".tempBox:last\").append(report)\r\n");
      out.write("							}\r\n");
      out.write("							}\r\n");
      out.write("				}else{\r\n");
      out.write("					console.log(\"수신실패\");\r\n");
      out.write("				}	\r\n");
      out.write("						\r\n");
      out.write("			}).fail(function(e){\r\n");
      out.write("	    		console.log(e);\r\n");
      out.write("	    	});\r\n");
      out.write("			}\r\n");
      out.write("				\r\n");
      out.write("		/*** 팔로우 테스트 ***/\r\n");
      out.write("\r\n");
      out.write("		// 팔로우 버튼 전환 function\r\n");
      out.write("		function changeDisplay_follow(firstVal, lastVal) {\r\n");
      out.write("			document.getElementById(\"followBtn\").style.display = firstVal; // 팔로우 하기 전\r\n");
      out.write("			document.getElementById(\"followingBtn\").style.display = lastVal; // 팔로우 누른 뒤\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 로그인 유저가 작성자를 팔로우 한 적이 있으면, 팔로우 버튼이 눌린 상태로 로드되어야 함\r\n");
      out.write("		if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkFollow}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("			changeDisplay_follow(\"none\", \"block\");\r\n");
      out.write("		} else {\r\n");
      out.write("			changeDisplay_follow(\"block\", \"none\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 로그인 유저와 작성자가 동일하다면 팔로우 버튼이 존재해서는 안됨\r\n");
      out.write("		if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_writer()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get('user_id')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") {\r\n");
      out.write("			document.getElementById(\"followBtn\").remove();\r\n");
      out.write("			document.getElementById(\"followingBtn\").remove();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 버튼 변동 처리\r\n");
      out.write("		document.addEventListener(\"click\", function(e) {\r\n");
      out.write("			if(e.target.id == \"followBtn\") { // 팔로우+ 버튼을 누를 때\r\n");
      out.write("				changeDisplay_follow(\"none\", \"block\");\r\n");
      out.write("				follow(\"add\");\r\n");
      out.write("			} else if(e.target.id == \"followingBtn\") { // 팔로잉 버튼을 누를 때 (언팔하겠다)\r\n");
      out.write("				changeDisplay_follow(\"block\", \"none\");\r\n");
      out.write("				follow(\"remove\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		// 팔로우 처리\r\n");
      out.write("		function follow(count) {\r\n");
      out.write("			let followCount = 0; // 서버로 보낼 값\r\n");
      out.write("			if(count == \"add\") {  // count값이 add이면 +1처리\r\n");
      out.write("				followCount = 1;\r\n");
      out.write("			} else if(count == \"remove\") { // count값이 remove이면 -1처리\r\n");
      out.write("				followCount = -1;\r\n");
      out.write("			}\r\n");
      out.write("			$.ajax({ \r\n");
      out.write("				type: \"post\",\r\n");
      out.write("				url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/followProc.bo\",\r\n");
      out.write("				data: { \r\n");
      out.write("					followCount: followCount,\r\n");
      out.write("					writer: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_writer()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				}\r\n");
      out.write("			}).done(function(rs) {\r\n");
      out.write("				console.log(rs);\r\n");
      out.write("			}).fail(function(e) {\r\n");
      out.write("				console.log(e);\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/*** 좋아요 버튼 ***/\r\n");
      out.write("\r\n");
      out.write("		// 좋아요 버튼 전환 function\r\n");
      out.write("		function changeDisplay_goodBtn(firstVal, lastVal) {\r\n");
      out.write("			document.getElementById(\"beforeGoodBtnBox\").style.display = firstVal;\r\n");
      out.write("			document.getElementById(\"afterGoodBtnBox\").style.display = lastVal;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//좋아요 버튼 변동\r\n");
      out.write("		//좋아요 기록할 경우 \r\n");
      out.write("		$(\"#beforeGoodBtn\").click(function(){\r\n");
      out.write("			// $(\"#beforeGoodBtnBox\").css(\"display\",\"none\");\r\n");
      out.write("			// $(\"#afterGoodBtnBox\").css(\"display\",\"block\");\r\n");
      out.write("			changeDisplay_goodBtn(\"none\", \"block\");\r\n");
      out.write("			goodCount(\"add\"); // 좋아요 +1 메서드 호출\r\n");
      out.write("		})\r\n");
      out.write("		//좋아요 해제할 경우\r\n");
      out.write("		$(\"#afterGoodBtn\").click(function(){\r\n");
      out.write("			 if (confirm(\"좋아요를 취소하시겠습니까?\")) {\r\n");
      out.write("                 changeDisplay_goodBtn(\"block\", \"none\");\r\n");
      out.write("                 goodCount(\"remove\");\r\n");
      out.write("             }\r\n");
      out.write("         })\r\n");
      out.write("\r\n");
      out.write("		// 좋아요 판별\r\n");
      out.write("		if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${likeCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") { \r\n");
      out.write("			// 유저가 이 게시물에 좋아요를 누른 적이 있다면, 좋아요 버튼이 눌린 상태로 게시물이 로드되어야 함\r\n");
      out.write("			// document.getElementById(\"beforeGoodBtnBox\").style.display = \"none\";\r\n");
      out.write("			// document.getElementById(\"afterGoodBtnBox\").style.display = \"block\";\r\n");
      out.write("			changeDisplay_goodBtn(\"none\", \"block\");\r\n");
      out.write("		} else { // 그런 적 없다면 그냥 비어있는 좋아요 버튼 출력\r\n");
      out.write("			// document.getElementById(\"beforeGoodBtnBox\").style.display = \"block\";\r\n");
      out.write("			// document.getElementById(\"afterGoodBtnBox\").style.display = \"none\";\r\n");
      out.write("			changeDisplay_goodBtn(\"block\", \"none\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 좋아요 Count처리\r\n");
      out.write("		function goodCount(count) {\r\n");
      out.write("			let goodCount = 0; // 서버로 보낼 값\r\n");
      out.write("			if(count == \"add\") {  // count값이 add이면 +1처리\r\n");
      out.write("				goodCount = 1;\r\n");
      out.write("			} else if(count == \"remove\") { // count값이 remove이면 -1처리\r\n");
      out.write("				goodCount = -1;\r\n");
      out.write("			}\r\n");
      out.write("			$.ajax({ \r\n");
      out.write("				type: \"post\",\r\n");
      out.write("				url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/goodCountProc.bo\",\r\n");
      out.write("				data: { // 로그인 한 유저 id는 Controller에서 세션으로 가져 올 생각\r\n");
      out.write("					goodCount: goodCount,\r\n");
      out.write("					postNo: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("					writer: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_writer()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				}\r\n");
      out.write("			}).done(function(rs) {\r\n");
      out.write("	        console.log(\"좋아요 수 :\" + rs);\r\n");
      out.write("				// 총 count수를 rs에 받아서, count수를 span태그에 삽입\r\n");
      out.write("				document.getElementsByClassName(\"totalCount\")[0].innerHTML = rs;\r\n");
      out.write("				document.getElementsByClassName(\"totalCount\")[1].innerHTML = rs;\r\n");
      out.write("			}).fail(function(e) {\r\n");
      out.write("				console.log(e);\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		 //댓글수정버튼 클릭시 확인,취소버튼 나오면서 인풋창 readonly해제          \r\n");
      out.write("		 $(document).on('click', '.btnReModify', function(e){\r\n");
      out.write("         var index = $(this).val();\r\n");
      out.write("            console.log(index);\r\n");
      out.write("         console.log(\"------------\");\r\n");
      out.write("         console.log($(\"div[value='\"+index+\"']\"));\r\n");
      out.write("         $(this).parent().css(\"display\", \"none\");\r\n");
      out.write("         $(this).parent().next().css(\"display\", \"block\");\r\n");
      out.write("         $(\"div[value='\"+index+\"']\").attr(\"hidden\",false);\r\n");
      out.write("      });\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		 //댓글수정버튼 클릭시 확인,취소버튼 나오면서 인풋창 readonly해제          \r\n");
      out.write("		//$(document).on('click', '#btnReModify', function(){\r\n");
      out.write("		//	$(this).parent().css(\"display\", \"none\");\r\n");
      out.write("		//	$(this).parent().next().css(\"display\", \"block\");\r\n");
      out.write("		//	$(\".modiBox\").attr(\"hidden\", false);\r\n");
      out.write("		//	\r\n");
      out.write("		//	\r\n");
      out.write("		//})\r\n");
      out.write("			\r\n");
      out.write("		//댓글삭제버튼 클릭시 댓글삭제\r\n");
      out.write("		$(document).on('click', '#btnReDelete', function(){\r\n");
      out.write("			let data = $(\"#cmtForm\").serialize();\r\n");
      out.write("			let value = $(this).val();\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				// aJax 댓글 삭제\r\n");
      out.write("				url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteProc.co?comment_no=\"+value\r\n");
      out.write("				, type : \"post\"\r\n");
      out.write("				, data : data				\r\n");
      out.write("			}).done(function(rs){\r\n");
      out.write("				if(rs == \"success\"){\r\n");
      out.write("					getCommentList();// 댓글 삭제에 성공하면 댓글 리스트 리로드\r\n");
      out.write("				}else if(rs == \"fail\"){\r\n");
      out.write("					alert(\"댓글 삭제에 실패했습니다.\"); // 댓글 삭제에 실패하면 alert \r\n");
      out.write("				}				\r\n");
      out.write("			}).fail(function(e){\r\n");
      out.write("				console.log(e);\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		$(document).on('click', '#btnReGo', function(){\r\n");
      out.write("         let data =  $(\"#modiCmtForm\").serialize();\r\n");
      out.write("         let value = $(this).val();\r\n");
      out.write("         console.log(value);\r\n");
      out.write("         let content = $(\"textarea[name='\"+value+\"']\").val();\r\n");
      out.write("         console.log(content);\r\n");
      out.write("         \r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/modifyProc.co?comment_no=\"+value+\"&comment_content=\" + content\r\n");
      out.write("            ,type : \"post\"\r\n");
      out.write("            ,data : data\r\n");
      out.write("         }).done(function(rs){\r\n");
      out.write("            getCommentList();\r\n");
      out.write("         }).fail(function(e){\r\n");
      out.write("            console.log(e);\r\n");
      out.write("         }); \r\n");
      out.write("         \r\n");
      out.write("      })\r\n");
      out.write("		//뒤로가기버튼 클릭 시 다시 댓글조회해서 초기화시킴\r\n");
      out.write("		$(document).on('click', '#btnReBack', function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"get\"\r\n");
      out.write("				,async:false\r\n");
      out.write("				, url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getCommentProc.co?post_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("				, dataType : \"json\"\r\n");
      out.write("			}).done(function(data){\r\n");
      out.write("				console.log(data);\r\n");
      out.write("				$(\".cmt-showBox\").empty();\r\n");
      out.write("				for(let cmt_dto of data){\r\n");
      out.write("							let comment = \r\n");
      out.write("							\"<div class='row mb-2 mx-1 my-3'>\"\r\n");
      out.write("							+ \"<div class='col-6 tempBox'>\"\r\n");
      out.write("							+ \"<div id='comment_content' name='comment_content'>\" + cmt_dto.content + \"</div>\"\r\n");
      out.write("							\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+ \"<div class='col-3'>\"\r\n");
      out.write("							+ cmt_dto.user_nickname +  \"|\" +cmt_dto.createdDate\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+ \"<div class='col-2 btnBox'>\"\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+\"<form method='post' id='modiCmtForm'>\"\r\n");
      out.write("							+ \"<div class='modiBox' value='\" + cmt_dto.comment_no + \"' hidden>\"\r\n");
      out.write("							+\"<div class='row mx-2 mb-2 mt-2'>\"\r\n");
      out.write("							+\"<div class='col'>\"\r\n");
      out.write("                			+\"<label>댓글수정</label>\"\r\n");
      out.write("	                		+\"</div>\"\r\n");
      out.write("	                		+\"<div class='row mx-2  comment-body'>\"\r\n");
      out.write("							+\"<div class='col-10 comment-input'>\"\r\n");
      out.write("							+\"<textarea id='modi_content_cmt' class='modi_content_cmt' name='\" +cmt_dto.comment_no+ \"' onkeydown='resize(this)' onkeyup='resize(this)'>\"+cmt_dto.content +\"</textarea>\"\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+\"<div class='col-2 comment-input'>\"\r\n");
      out.write("							+\"<button type='button' id='btnReGo'  value='\" + cmt_dto.comment_no + \"' class='btn btn-dark btnReGo'>등록</button>\"\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+\"</div>\"\r\n");
      out.write("							+ \"</div>\"\r\n");
      out.write("							+\"</form>\"\r\n");
      out.write("							\r\n");
      out.write("							$(\".cmt-showBox\").append(comment);\r\n");
      out.write("						\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get('user_id')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" ==  cmt_dto.user_id){\r\n");
      out.write("									let btns=\"<div class='col-3' class='reBtnBox' id='beforeReBtnBox'>\"\r\n");
      out.write("									+\" <button type='button' id='btnReModify' value='\" +cmt_dto.comment_no + \"' class='btn btn-dark btn-sm btnReModify'>수정</button>\"\r\n");
      out.write("									+ \"<button type='button' id='btnReDelete' value='\" + cmt_dto.comment_no + \"' class='btn btn-dark btn-sm'>삭제</button>\"\r\n");
      out.write("									+\"</div>\"\r\n");
      out.write("									+\"<div class='col-3' class='reBtnBox' id='afterReBtnBox'>\"\r\n");
      out.write("									+\"<button type='button' id='btnReBack' class='btn btn-dark btn-sm'>취소</button>\"\r\n");
      out.write("									+\"</div>\"\r\n");
      out.write("									\r\n");
      out.write("									$(\".btnBox:last\").append(btns);\r\n");
      out.write("								}\r\n");
      out.write("							//자기게시글에는 신고X\r\n");
      out.write("							 if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get('user_id')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" != cmt_dto.user_id){\r\n");
      out.write("								\r\n");
      out.write("								let report =  \"<button tpye='button' id = 'cmtReport' value='\" + cmt_dto.comment_no + \"' class='btn btn-danger btn-sm cmtReport'>신고</button>\"\r\n");
      out.write("								\r\n");
      out.write("								$(\".tempBox:last\").append(report)\r\n");
      out.write("							}\r\n");
      out.write("							}\r\n");
      out.write("						\r\n");
      out.write("			}).fail(function(e){\r\n");
      out.write("	    		console.log(e);\r\n");
      out.write("	    	});\r\n");
      out.write("			\r\n");
      out.write("	})\r\n");
      out.write("	// 신고버튼 클릭 처리 btnReport, cmtReport\r\n");
      out.write("	$(\"#btnReport\").on(\"click\", function(){\r\n");
      out.write("		let url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toReport.re?post_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&report_type=1&reported_comment_no=0\";\r\n");
      out.write("		let name = \"신고하기\";\r\n");
      out.write("		let option = \"width=750, height=760, top=300\";\r\n");
      out.write("		window.open(url, name, option);\r\n");
      out.write("	})\r\n");
      out.write("	$(document).on('click', '#cmtReport', function(){\r\n");
      out.write("		let val = $('#cmtReport').val();\r\n");
      out.write("		console.log(val);\r\n");
      out.write("		let url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toReport.re?post_no=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&report_type=2&reported_comment_no=\"+val;\r\n");
      out.write("		let name = \"신고하기\";\r\n");
      out.write("		let option = \"width=750, height=760, top=300\";\r\n");
      out.write("		window.open(url, name, option);\r\n");
      out.write("	})\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /board/postDetail.jsp(248,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_writer() != loginSession.get('user_id')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            			<div class=\"col-1\" id=\"reportBtnBox\">\r\n");
          out.write("	            				<button type=\"button\" value=\"게시글번호 넣어주세요.\" class=\"btn btn-danger\" id=\"btnReport\">\r\n");
          out.write("	            					<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-exclamation-diamond-fill\" viewBox=\"0 0 16 16\">\r\n");
          out.write("	  								<path d=\"M9.05.435c-.58-.58-1.52-.58-2.1 0L.436 6.95c-.58.58-.58 1.519 0 2.098l6.516 6.516c.58.58 1.519.58 2.098 0l6.516-6.516c.58-.58.58-1.519 0-2.098L9.05.435zM8 4c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995A.905.905 0 0 1 8 4zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\"/>\r\n");
          out.write("									</svg>\r\n");
          out.write("									<span>신고</span>\r\n");
          out.write("	            				</button>\r\n");
          out.write("	            			</div>\r\n");
          out.write("            			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /board/postDetail.jsp(266,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginSession}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            			<div class=\"col-1 mb-2\">\r\n");
          out.write("	            				<button type=\"button\" class=\"btn btn-dark\" id=\"followingBtn\">팔로잉</button>\r\n");
          out.write("	            				<button type=\"button\" class=\"btn btn-dark\" id=\"followBtn\">팔로우+</button>\r\n");
          out.write("	            			</div>\r\n");
          out.write("            			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /board/postDetail.jsp(296,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("id");
      // /board/postDetail.jsp(296,14) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/board/postDetail.jsp(296,14) '${dto.getPost_writer()}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dto.getPost_writer()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /board/postDetail.jsp(297,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id eq loginSession.get('user_id')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            		<div class=\"row my-4 btnBox\" id=\"btnsBox\">\r\n");
          out.write("	            			<div class=\"col\">\r\n");
          out.write("		            			<button type=\"button\" id=\"btnModify\" class=\"btn btn-dark\">수정</button>\r\n");
          out.write("		            			<button type=\"button\" id=\"btnDelete\" class=\"btn btn-dark\">삭제</button>\r\n");
          out.write("	            			</div>\r\n");
          out.write("	            		</div>\r\n");
          out.write("	            		<!-- 수정버튼 누를경우 완료, 취소 버튼 나타내기 -->\r\n");
          out.write("	            		<div class=\"row my-4 btnBox\" id=\"btnModifyDetailBox\">\r\n");
          out.write("	            			<div class=\"col\">\r\n");
          out.write("	            				<button type=\"button\" id=\"btnGo\" class=\"btn btn-dark\">등록</button>\r\n");
          out.write("		            			<button type=\"button\" id=\"btnBack\" class=\"btn btn-dark\">취소</button>\r\n");
          out.write("	            			</div>\r\n");
          out.write("	            		</div>\r\n");
          out.write("            		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /board/postDetail.jsp(314,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginSession}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            		<div class=\"row my-2 btnBox\"id=\"beforeGoodBtnBox\">\r\n");
          out.write("	            			<div class=\"col\">\r\n");
          out.write("	            				<button type=\"button\" id=\"beforeGoodBtn\" class=\"btn btn-light\">\r\n");
          out.write("									<span class=\"totalCount\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-hand-thumbs-up\" viewBox=\"0 0 16 16\">\r\n");
          out.write("									  <path d=\"M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z\"/>\r\n");
          out.write("									</svg>\r\n");
          out.write("								</button>\r\n");
          out.write("	            			</div>\r\n");
          out.write("	            		</div>\r\n");
          out.write("	            			<!-- 버튼 누른 후 좋아요 -->\r\n");
          out.write("	            		<div class=\"row my-2 btnBox\"id=\"afterGoodBtnBox\">\r\n");
          out.write("	            			<div class=\"col\">\r\n");
          out.write("	            				<button type=\"button\" id=\"afterGoodBtn\" class=\"btn btn-light\">\r\n");
          out.write("									<span class=\"totalCount\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-hand-thumbs-up-fill\" viewBox=\"0 0 16 16\">\r\n");
          out.write("									  <path d=\"M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z\"/>\r\n");
          out.write("									</svg>\r\n");
          out.write("								</button>\r\n");
          out.write("	            			</div>\r\n");
          out.write("	            		</div>\r\n");
          out.write("            		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
