/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-21 08:17:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1638513134000L));
    _jspx_dependants.put("jar:file:/D:/workspace_photofolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/photofolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("	integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $(\"#header\").load(\"resources/header/header.jsp\")      \r\n");
      out.write("         });\r\n");
      out.write("  </script>\r\n");
      out.write("<title>유저 페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("			* {\r\n");
      out.write("				box-sizing: border-box;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		/* ========== 유저 페이지 영역 ========== */\r\n");
      out.write("		\r\n");
      out.write("		/* 유저 컨테이너 */\r\n");
      out.write("		.userContainer {\r\n");
      out.write("			width: 1600px;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("			margin-top: 50px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 프로필, 알림 DIV */\r\n");
      out.write("		.profileContainer {\r\n");
      out.write("			height: 869px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 프로필 박스 */\r\n");
      out.write("		.profileBox {\r\n");
      out.write("			border: 1px solid lightgray;\r\n");
      out.write("			padding: 20px;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			margin-top: 10px;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 프로필 영역 */\r\n");
      out.write("		#profileImg {\r\n");
      out.write("			border-radius: 100%;\r\n");
      out.write("			background-color: #9db0e8;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			height: 100px;\r\n");
      out.write("			overflow:hidden;\r\n");
      out.write("			padding:0;\r\n");
      out.write("		}\r\n");
      out.write("		/* 프로필 기본이미지 */\r\n");
      out.write("		#profileImg>img {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 100%;\r\n");
      out.write("			object-fit:cover;\r\n");
      out.write("		}\r\n");
      out.write("		/* 팔로우 버튼 */\r\n");
      out.write("		#btnFollow {\r\n");
      out.write("			border: none;\r\n");
      out.write("			background-color: #5656c4;\r\n");
      out.write("			color: white;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 팔로잉 버튼 */\r\n");
      out.write("		#btnFollowing {\r\n");
      out.write("			border: none;\r\n");
      out.write("			background-color: #5656c4;\r\n");
      out.write("			color: white;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		.flBtn{\r\n");
      out.write("			position:relative;\r\n");
      out.write("			left:120px;\r\n");
      out.write("			bottom:60px;\r\n");
      out.write("		}\r\n");
      out.write("		#follow{\r\n");
      out.write("			height:10px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 프로필 수정 버튼 */\r\n");
      out.write("		#btnEdit {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			border: none;\r\n");
      out.write("			background-color: #5656c4;\r\n");
      out.write("			color: white;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 20px;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("		/* 알림창 영역 */\r\n");
      out.write("		\r\n");
      out.write("		/* 알림 창 박스 */\r\n");
      out.write("		.noticeBox {\r\n");
      out.write("			border: 1px solid lightgray;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			margin: 0%;\r\n");
      out.write("			margin-top: 20px;\r\n");
      out.write("			height: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 알림 제목 */\r\n");
      out.write("		.noticeTitle {\r\n");
      out.write("			border-bottom: 1px solid lightgray;\r\n");
      out.write("			background-color: #5656c4;\r\n");
      out.write("			color: white;\r\n");
      out.write("			font-weight: 900;\r\n");
      out.write("			font-size: 25px;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			padding: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 알림 내용 */\r\n");
      out.write("		.noticeContent {\r\n");
      out.write("			padding: 20px;\r\n");
      out.write("			overflow: scroll;\r\n");
      out.write("			padding: 20px;\r\n");
      out.write("			height: 95%;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 게시글 조회,등록 영역 */\r\n");
      out.write("		.boardList {\r\n");
      out.write("			margin-top: 5px;\r\n");
      out.write("			margin-left: 0px;\r\n");
      out.write("			margin-right: 5px;\r\n");
      out.write("			padding: 0%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.post {\r\n");
      out.write("			width: 390px;\r\n");
      out.write("			height: 390px;\r\n");
      out.write("			padding: 0%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 등록 상단 */\r\n");
      out.write("		.postDetail {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 100%;\r\n");
      out.write("			margin-left: 2px;\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.postDetail>:first-child {\r\n");
      out.write("			height: 100%;\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 체크박스 span태그 */\r\n");
      out.write("		.checkSeq {\r\n");
      out.write("			float: left;\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			top: 30px;\r\n");
      out.write("			left: 30px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 인풋 checkbox */\r\n");
      out.write("		.checkSeq input {\r\n");
      out.write("			width: 30px;\r\n");
      out.write("			height: 30px;\r\n");
      out.write("		}\r\n");
      out.write("		/* top삭제버튼 */\r\n");
      out.write("		.btnDeleteTop {\r\n");
      out.write("			float: right;\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			left: 320px;\r\n");
      out.write("			top: 30px;\r\n");
      out.write("			width: 100px;\r\n");
      out.write("			height: 100px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 버튼tag */\r\n");
      out.write("		.btnDelete {\r\n");
      out.write("			border: none;\r\n");
      out.write("			background-color: transparent;\r\n");
      out.write("		}\r\n");
      out.write("		/* top삭제버튼img */\r\n");
      out.write("		.btnDeleteTop svg {\r\n");
      out.write("			width: 30px;\r\n");
      out.write("			height: 30px;\r\n");
      out.write("			color: gray;\r\n");
      out.write("			background-color: transparent;\r\n");
      out.write("		}\r\n");
      out.write("		/* top삭제버튼img 호버*/\r\n");
      out.write("		.btnDeleteTop svg:hover {\r\n");
      out.write("			width: 30px;\r\n");
      out.write("			height: 30px;\r\n");
      out.write("			color: black;\r\n");
      out.write("			background-color: transparent;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 상단  */\r\n");
      out.write("		.postDetail {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 85%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글추가 버튼 */\r\n");
      out.write("		.btnInsert {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 100%;\r\n");
      out.write("			padding: 0%;\r\n");
      out.write("			margin: 0px;\r\n");
      out.write("			background-color: transparent;\r\n");
      out.write("			border: none;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 추가 버튼 (+)이미지 */\r\n");
      out.write("		.btnInsert>svg {\r\n");
      out.write("			width: 50%;\r\n");
      out.write("			height: 50%;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			color: gray;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 추가 버튼 (+)이미지 */\r\n");
      out.write("		.btnInsert>svg:hover {\r\n");
      out.write("			width: 50%;\r\n");
      out.write("			height: 50%;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			color: black;\r\n");
      out.write("		}\r\n");
      out.write("		/* 사용자 이미지 DIV */\r\n");
      out.write("		.thumbnail_img {\r\n");
      out.write("		    width: 350px;\r\n");
      out.write("		    height: 20rem;\r\n");
      out.write("		}\r\n");
      out.write("		/* 버튼 파일 사용자 이미지:hover */\r\n");
      out.write("		.btnInsert>img:hover {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			height: 100%;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			border: 5px solid black;\r\n");
      out.write("			padding: 0%;\r\n");
      out.write("			margin: 0%;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 등록 디테일 하단 */\r\n");
      out.write("		.barDetailBox {\r\n");
      out.write("			height: 12%;\r\n");
      out.write("			width: 93.5%;\r\n");
      out.write("			padding: 0px;\r\n");
      out.write("			margin-left: 15px;\r\n");
      out.write("			margin-top: 5px;\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			border: 1px solid #9db0e8;\r\n");
      out.write("			background-color: #9db0e8;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 등록 Input 타이틀 */\r\n");
      out.write("		.barDetailTitle {\r\n");
      out.write("			border: none;\r\n");
      out.write("			font-size: 17px;\r\n");
      out.write("			font-weight: 900;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("			background-color: #9db0e8;\r\n");
      out.write("			color: white;\r\n");
      out.write("			width:100%;\r\n");
      out.write("			padding-left: 10px;\r\n");
      out.write("			padding-top: 8px;\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("		}\r\n");
      out.write("		.viewBox{\r\n");
      out.write("			margin-top:8px;\r\n");
      out.write("			color:white;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 등록 Input 타이틀:focus */\r\n");
      out.write("		.barDetailTitle:focus {\r\n");
      out.write("			outline: none;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시글 수정 버튼 */\r\n");
      out.write("		.likeBox {\r\n");
      out.write("			border: none;\r\n");
      out.write("			font-size: 17px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-family: 'Jua', sans-serif;\r\n");
      out.write("			background-color: #9db0e8;\r\n");
      out.write("			color: white;\r\n");
      out.write("			padding-top: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		/* 좋아요 아이콘 */\r\n");
      out.write("		.likeBox>svg {\r\n");
      out.write("			width: 45%;\r\n");
      out.write("			height: 45%;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 페이징 영역*/\r\n");
      out.write("		/* Prev 버튼 */\r\n");
      out.write("		#btnPrev {\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			font-size: 20px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			background-color: #5656c4;\r\n");
      out.write("			color: white;\r\n");
      out.write("			border: none;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		#btnNext {\r\n");
      out.write("			border-radius: 5px;\r\n");
      out.write("			font-size: 20px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			background-color: #5656c4;\r\n");
      out.write("			color: white;\r\n");
      out.write("			border: none;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/**** *modal 기본 디자인 ****/\r\n");
      out.write("        .modal-title {\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-family: 'Jua', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal_table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal_userImg_wrapper {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #modal_userImg {\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            border-radius: 75%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal_userId {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal_userFollow {\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("		.dynamic_btnFollow_off { /*동적 생성 버튼2*/\r\n");
      out.write("			/* display: none; */\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("        /*modal 스크롤 적용*/\r\n");
      out.write("        .modal-dialog {\r\n");
      out.write("            overflow-y: initial !important\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-body {\r\n");
      out.write("            height: 50vh;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #followBtn, #followingBtn{\r\n");
      out.write("    		height:80px;\r\n");
      out.write("			width:100px;\r\n");
      out.write("			background-color:rgb(86, 86, 196);\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- ======================================== 헤더 ======================================== -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"Wrapper\">\r\n");
      out.write("		<div id=\"header\"></div>\r\n");
      out.write("\r\n");
      out.write("	<!-- ======================================== 유저 페이지 ======================================== -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"userContainer\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-3 profileContainer\">\r\n");
      out.write("				<!-- 프로필창 -->\r\n");
      out.write("				<div class=\"row profileBox m-0\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 프로필 사진 -->\r\n");
      out.write("					<div id=\"profileImg\">\r\n");
      out.write("				            		<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getProfilePhoto_path() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("					<!-- 프로필(이름, 팔로우 버튼) -->\r\n");
      out.write("					<div class=\"col-8 mb-5\" id=\"\">\r\n");
      out.write("						<div class=\"mb-1\">\r\n");
      out.write("								<h4> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_nickname() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<button type=\"button\" class=\"mb-1\" id=\"btnFollow\">follower\r\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countFollower}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<button type=\"button\" id=\"btnFollowing\">follwing ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${countFollowing}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"follow\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("							\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 프로필 수정 버튼 -->\r\n");
      out.write("					\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 알림창 -->\r\n");
      out.write("				<div class=\"row noticeBox\">\r\n");
      out.write("					<div class=\"col-12 noticeTitle d-flex justify-content-center\">\r\n");
      out.write("						Notice</div>\r\n");
      out.write("					<div class=\"col-12 noticeContent\">\r\n");
      out.write("				    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-9\">\r\n");
      out.write("				<!-- 게시글 조회,등록  -->\r\n");
      out.write("				<div class=\"row boardList m-0\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<!-- forEach -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 게시글 col -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 페이징 -->\r\n");
      out.write("		<div class=\"col-12 d-flex justify-content-center mt-5 mb-5\">\r\n");
      out.write("			<nav class=\"row\" aria-label=\"Page navigation example\">\r\n");
      out.write("				<div class=\"col-12 d-flex justify-content-center\">\r\n");
      out.write("					<ul class=\"pagination justify-content-center\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						<!-- startNavi -> endNavi -->\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!------------- Modal --------------->\r\n");
      out.write("    <div class=\"modal fade\" id=\"followModal\" role=\"dialog\"> \r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Modal content-->\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <!--팔로워 or 팔로잉 목록 헤더가 들어감-->\r\n");
      out.write("                    <h4 class=\"modal-title\"></h4>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <table class=\"modal_table\">\r\n");
      out.write("                        <!--유저 목록 들어갈 자리-->\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"count\" value=\"1\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--modal 호출 버튼(hidden)-->\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#followModal\" id=\"btnModalCall\"\r\n");
      out.write("        hidden>\r\n");
      out.write("    </button>>\r\n");
      out.write("\r\n");
      out.write("	 <script>\r\n");
      out.write("		document.addEventListener(\"click\", function(e) {\r\n");
      out.write("			let id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			if(e.target.id == \"btnFollowing\") {\r\n");
      out.write("				console.log(\"버튼에 대한 계정id : \" + id);\r\n");
      out.write("				const url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getListFollowingProc.bo?user_id=\"+id;\r\n");
      out.write("				document.getElementsByClassName(\"modal-header\")[0].innerHTML = \"팔로잉 목록\";\r\n");
      out.write("				// setModal(url);\r\n");
      out.write("				getListFollow(url);\r\n");
      out.write("			} else if(e.target.id == \"btnFollow\") {\r\n");
      out.write("				console.log(\"버튼에 대한 계정id : \" + id);\r\n");
      out.write("				const url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getListFollowerProc.bo?user_id=\"+id;\r\n");
      out.write("				document.getElementsByClassName(\"modal-header\")[0].innerHTML = \"팔로워 목록\";\r\n");
      out.write("				// setModal(url);\r\n");
      out.write("				getListFollow(url);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// user가 팔로우하는 유저 목록 가져오기\r\n");
      out.write("	      function getListFollow(url) {\r\n");
      out.write("	         $(\".modal_table\").empty(); // modal창 기존 데이터 제거\r\n");
      out.write("	         $.ajax({ \r\n");
      out.write("	            type: \"get\",\r\n");
      out.write("	            url: url,\r\n");
      out.write("	            dataType: \"json\"\r\n");
      out.write("	         }).done(function(rs) { \r\n");
      out.write("	            let listFollower = \"\"; // 리스트 담을 공간\r\n");
      out.write("	            for(let list of rs) { \r\n");
      out.write("	               if(checkFollow(list.user_id)) { // 팔로우 상태 판별\r\n");
      out.write("	                  listFollower = '<tr>'\r\n");
      out.write("	                            + '<td class=\"modal_userImg_wrapper\">'\r\n");
      out.write("	                                + '<img id=\"modal_userImg\" src=\"' + list.profilePhoto_path + '\">'\r\n");
      out.write("	                            + '</td>'\r\n");
      out.write("	                            + '<td class=\"modal_userID\">' + list.user_nickname + '</td>';\r\n");
      out.write("	                        if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get(\"user_id\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" !== list.user_id) { // 팔로워 목록에 로그인 유저 본인이 있으면 버튼 제외\r\n");
      out.write("	                            listFollower += '<td class=\"modal_userFollow\">'\r\n");
      out.write("	                     + '<buttton class=\"btn btn-primary dynamic_btnFollow_on\" id=\"' + list.user_id + '\" value=\"\">팔로잉</button>'\r\n");
      out.write("	                            + '</td>'\r\n");
      out.write("	                            + '<td class=\"modal_userFollow\" style=\"display: none;\">'\r\n");
      out.write("	                                + '<buttton class=\"btn btn-outline-primary dynamic_btnFollow_off\" id=\"' + list.user_id + '\" value=\"\">팔로우</button>'\r\n");
      out.write("	                            + '</td>';\r\n");
      out.write("	                        }\r\n");
      out.write("	               } else {\r\n");
      out.write("	                  listFollower = '<tr>'\r\n");
      out.write("	                  + '<td class=\"modal_userImg_wrapper\">'\r\n");
      out.write("	                     + '<img id=\"modal_userImg\" src=\"' + list.profilePhoto_path + '\">'\r\n");
      out.write("	                  + '</td>'\r\n");
      out.write("	                  + '<td class=\"modal_userID\">' + list.user_nickname + '</td>';\r\n");
      out.write("	                        if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get(\"user_id\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" !== list.user_id) { // 팔로워 목록에 로그인 유저 본인이 있으면 버튼 제외\r\n");
      out.write("	                            listFollower += '<td class=\"modal_userFollow\" style=\"display: none;\">'\r\n");
      out.write("	                      + '<buttton class=\"btn btn-primary dynamic_btnFollow_on\" id=\"' + list.user_id + '\" value=\"\">팔로잉</button>'\r\n");
      out.write("	                            + '</td>'\r\n");
      out.write("	                            + '<td class=\"modal_userFollow\">'\r\n");
      out.write("	                                + '<buttton class=\"btn btn-outline-primary dynamic_btnFollow_off\" id=\"' + list.user_id + '\" value=\"\">팔로우</button>'\r\n");
      out.write("	                            + '</td>';\r\n");
      out.write("	                        }\r\n");
      out.write("	               }\r\n");
      out.write("	               $(\".modal_table\").append(listFollower); // 리스트 삽입\r\n");
      out.write("	               document.getElementById(\"btnModalCall\").click(); // modal창 열기\r\n");
      out.write("	            }\r\n");
      out.write("	         }).fail(function(e) {\r\n");
      out.write("	            console.log(e);\r\n");
      out.write("	         });\r\n");
      out.write("	      }\r\n");
      out.write("\r\n");
      out.write("		// 팔로우 여부 확인\r\n");
      out.write("		function checkFollow(id) {\r\n");
      out.write("			let tmp = false;\r\n");
      out.write("			$.ajax({ // id끼리 비교하여, 팔로우 중인지 확인 후 boolean리턴\r\n");
      out.write("				type: \"post\",\r\n");
      out.write("				url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/checkFollowProc.bo\",\r\n");
      out.write("				async: false, // 동기식으로 처리해야 리턴값 제대로 처리됨\r\n");
      out.write("				data: {\r\n");
      out.write("					id: id\r\n");
      out.write("				}\r\n");
      out.write("			}).done(function(rs){\r\n");
      out.write("				if(rs == \"true\") tmp = true;\r\n");
      out.write("			}).fail(function(e){\r\n");
      out.write("				console.log(e);\r\n");
      out.write("			});\r\n");
      out.write("			return tmp;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 팔로우 +1\r\n");
      out.write("		$(document).on(\"click\", \".dynamic_btnFollow_off\", function(e) { // 바인딩 처리\r\n");
      out.write("			let id = e.target.getAttribute(\"id\");\r\n");
      out.write("			$(e.target).parent().prev().show();\r\n");
      out.write("			$(e.target).parent().hide();\r\n");
      out.write("			follow(\"add\", id); // 팔로우 +1\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		// 팔로잉 버튼 클릭(언팔하겠다)\r\n");
      out.write("		$(document).on(\"click\", \".dynamic_btnFollow_on\", function(e) { // 바인딩 처리\r\n");
      out.write("			let id = e.target.getAttribute(\"id\");\r\n");
      out.write("			$(e.target).parent().next().show();\r\n");
      out.write("			$(e.target).parent().hide();\r\n");
      out.write("			follow(\"remove\", id); // 팔로우 +1\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("        // 팔로우 버튼 노출(modal아님)\r\n");
      out.write("        if(checkFollow(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\")) {\r\n");
      out.write("            $(\"#followBtn\").hide();\r\n");
      out.write("            $(\"#followingBtn\").show();\r\n");
      out.write("        } else {\r\n");
      out.write("            $(\"#followBtn\").show();\r\n");
      out.write("            $(\"#followingBtn\").hide();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 팔로우 버튼(modal아님)\r\n");
      out.write("		document.addEventListener(\"click\", function(e) {\r\n");
      out.write("            if(e.target.id == \"followBtn\") {\r\n");
      out.write("                follow(\"add\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("                $(\"#followBtn\").hide();\r\n");
      out.write("                $(\"#followingBtn\").show();\r\n");
      out.write("            } else if(e.target.id == \"followingBtn\" && confirm(\"팔로우를 취소하시겠습니까?\")) {\r\n");
      out.write("                follow(\"remove\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("                $(\"#followBtn\").show();\r\n");
      out.write("                $(\"#followingBtn\").hide();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("		// 팔로우 처리\r\n");
      out.write("		function follow(count, id) {\r\n");
      out.write("			let followCount = 0; // 서버로 보낼 값\r\n");
      out.write("			if(count == \"add\") {  // count값이 add이면 +1처리\r\n");
      out.write("				followCount = 1;\r\n");
      out.write("			} else if(count == \"remove\") { // count값이 remove이면 -1처리\r\n");
      out.write("				followCount = -1;\r\n");
      out.write("			}\r\n");
      out.write("			$.ajax({ \r\n");
      out.write("				type: \"post\",\r\n");
      out.write("				url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/followProc.bo\",\r\n");
      out.write("				data: { \r\n");
      out.write("					followCount: followCount,\r\n");
      out.write("					writer: id \r\n");
      out.write("				}\r\n");
      out.write("			}).done(function(rs) {\r\n");
      out.write("				console.log(rs);\r\n");
      out.write("			}).fail(function(e) {\r\n");
      out.write("				console.log(e);\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(document).ready(function () {\r\n");
      out.write("			 $(\".noti_table\").append(notiShare); // header에서 noti받아옴\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("		integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("//	단일 삭제\r\n");
      out.write("	$(\".btnDelete\").click(function(){\r\n");
      out.write("		let val = this.value;\r\n");
      out.write("		location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteProc.bo?post_no=\" +val;\r\n");
      out.write("		console.log(val);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("		//Edit profile 버튼 처리 ->마이페이지로 \r\n");
      out.write("		$(\"#btnEdit\").click(function(){\r\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toMyPage.mem?\";\r\n");
      out.write("		})\r\n");
      out.write("	\r\n");
      out.write("		// 게시글 상세 조회로 이동\r\n");
      out.write("		$(\".thumbnail\").on(\"click\",function() {\r\n");
      out.write("		     location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toDetailPost.bo\";\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /board/userPage.jsp(406,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id() ne loginSession.get('user_id') }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"col-1 mb-2 flBtn\">\r\n");
          out.write("			            				<button type=\"button\" class=\"btn btn-dark\" id=\"followingBtn\">팔로잉</button>\r\n");
          out.write("			            				<button type=\"button\" class=\"btn btn-dark\" id=\"followBtn\">팔로우+</button>\r\n");
          out.write("		            			</div>\r\n");
          out.write("	            			 ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /board/userPage.jsp(418,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id() == loginSession.get('user_id') }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div class=\"col-12 mb-3\" id=\"\">\r\n");
          out.write("								<button type=\"button\" id=\"btnEdit\">Edit Profile</button>\r\n");
          out.write("							</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /board/userPage.jsp(432,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mdto.getUser_id() eq loginSession.get('user_id')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				        <table class=\"noti_table\">\r\n");
          out.write("				<!-- 알림 내용 추가 됨 -->\r\n");
          out.write("				        </table>\r\n");
          out.write("				    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /board/userPage.jsp(445,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/board/userPage.jsp(445,5) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/userPage.jsp(445,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("						<!-- 1번 게시글 등록 -->\r\n");
            out.write("					\r\n");
            out.write("						<div class=\"col-4 post form-control pt-2\">\r\n");
            out.write("\r\n");
            out.write("							<!-- 게시글 등록 '상단'(체크박스, 제거버튼), (+)이미지, 타이틀이미지 -->\r\n");
            out.write("							<div class=\"row postDetail\">\r\n");
            out.write("								<div class=\"col-12\">\r\n");
            out.write("									<span class=\"checkSeq\"> <input type=\"checkbox\"\r\n");
            out.write("										class=\"checkbox\" style=\"visibility: hidden;\">\r\n");
            out.write("									</span>\r\n");
            out.write("\r\n");
            out.write("									<!-- 상단 제거버튼 -->\r\n");
            out.write("									<span class=\"btnDeleteTop\">\r\n");
            out.write("										");
            if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("									</span>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("									<!-- 썸네일 -->\r\n");
            out.write("								  	<div class=\"thumbnail d-flex justify-content-center\">\r\n");
            out.write("								  	 	");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("									</div>\r\n");
            out.write("\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<!-- 게시글 '하단' 번호, 타이틀, 좋아요아이콘,  -->\r\n");
            out.write("							<div class=\"row barDetailBox\">\r\n");
            out.write("								<div class=\"col-9 p-0 m-0\">\r\n");
            out.write("									<input type=\"text\" class=\"barDetailTitle\"\r\n");
            out.write("										value=\"no");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write(':');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_title()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("										readonly>\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"col-3 viewBox\">\r\n");
            out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\"\r\n");
            out.write("										fill=\"currentColor\" class=\"bi bi-eye-fill\" viewBox=\"0 0 16 16\">\r\n");
            out.write("										  <path d=\"M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z\" />\r\n");
            out.write("										  <path\r\n");
            out.write("											d=\"M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z\" />\r\n");
            out.write("									</svg>\r\n");
            out.write("									");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_view_count()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					\r\n");
            out.write("					\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /board/userPage.jsp(460,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginSession.get('user_id') == dto.getPost_writer() }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<button type=\"button\" class=\"btnDelete\"value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("											<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\"\r\n");
          out.write("												height=\"16\" fill=\"currentColor\" class=\"bi bi-x-circle\"\r\n");
          out.write("												viewBox=\"0 0 16 16\">\r\n");
          out.write("                                                <path\r\n");
          out.write("													d=\"M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z\" />\r\n");
          out.write("                                                <path\r\n");
          out.write("													d=\"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z\" />\r\n");
          out.write("                                            </svg>\r\n");
          out.write("										</button>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /board/userPage.jsp(477,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/board/userPage.jsp(477,13) '${file_list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${file_list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /board/userPage.jsp(477,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("file");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("								  	 	");
            if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("	\r\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /board/userPage.jsp(478,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no() == file.getPost_no() }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								  		<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/toDetailPost.bo?post_no=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getPost_no()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&currentPage=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('currentPage')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("											<img class=\"thumbnail_img\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/files/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.getSystem_name()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("										</a>	\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /board/userPage.jsp(526,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('needPrev') eq true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li class=\"page-item\"><a class=\"page-link\"\r\n");
          out.write("								href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/toUserPage.bo?currentPage=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('startNavi')-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Previous</a>\r\n");
          out.write("							</li>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /board/userPage.jsp(532,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("i");
      // /board/userPage.jsp(532,6) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('startNavi')}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /board/userPage.jsp(532,6) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('endNavi')}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<li class=\"page-item\"><a class=\"page-link\"\r\n");
            out.write("								href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/toUserPage.bo?currentPage=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("							</li>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /board/userPage.jsp(539,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('needNext') eq true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li class=\"page-item\"><a class=\"page-link\"\r\n");
          out.write("								href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/toUserPage.bo?currentPage=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${naviMap.get('endNavi')+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Next</a>\r\n");
          out.write("							</li>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }
}
