/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-16 04:32:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("        integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <title>login</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body{\r\n");
      out.write("            background-color:rgb(86, 86, 196);\r\n");
      out.write("        }\r\n");
      out.write("        /*container*/\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 680px;\r\n");
      out.write("            margin-top: 80px;\r\n");
      out.write("            padding: 70px;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            -webkit-border-radius: 10px;\r\n");
      out.write("            -moz-border-radius: 10px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("            -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("            box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /*** 로그인 영역 ***/\r\n");
      out.write("\r\n");
      out.write("        /*Login 타이틀 폰트*/\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        /*로그인 관련 요소 wrapper*/\r\n");
      out.write("        .loginElements-Wrapper {\r\n");
      out.write("            width: 60%;\r\n");
      out.write("        }\r\n");
      out.write("        /*입력창, 로그인 버튼*/\r\n");
      out.write("        .loginElements-Wrapper > #id,#password,#btnLogin { \r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        /*로그인 버튼*/\r\n");
      out.write("        .loginElements-Wrapper > #btnLogin {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /*카카오 로그인 버튼 이미지 wrapper*/\r\n");
      out.write("        #btnKakaoLogin-Wrapper {\r\n");
      out.write("            height: 38px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            background-color: #FEE500;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        /*카카오 로그인 버튼 이미지*/\r\n");
      out.write("        .loginElements-Wrapper > img {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /*id,pw 찾기 버튼*/\r\n");
      out.write("        .findWrapper > a {\r\n");
      out.write("            color: gray;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .findWrapper > a:hover {\r\n");
      out.write("            color: gray;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*** modal영역 ***/\r\n");
      out.write("\r\n");
      out.write("        /*default hide*/\r\n");
      out.write("        #findEmailArea,\r\n");
      out.write("        #sendNum_Wrapper,\r\n");
      out.write("        #sendNum_Wrapper2,\r\n");
      out.write("        #btnModalCall,\r\n");
      out.write("        #btnModalCall2,\r\n");
      out.write("        #secondWrap {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        /*인증 관련 버튼들*/\r\n");
      out.write("        .clsBtn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--로그인 영역-->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loginProc.mem\" method=\"post\" id=\"formLogin\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col d-flex justify-content-center\">\r\n");
      out.write("                    <h1>Login</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!--아이디 입력-->\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center mt-5\">\r\n");
      out.write("                    <div class=\"form-floating loginElements-Wrapper\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"id\" name=\"user_id\" placeholder=\"\">\r\n");
      out.write("                        <label for=\"id\">ID</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--패스워드 입력-->\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center mt-2\">\r\n");
      out.write("                    <div class=\"form-floating loginElements-Wrapper\">\r\n");
      out.write("                        <input type=\"password\" class=\"form-control clsInput\" id=\"password\" name=\"user_password\"\r\n");
      out.write("                            placeholder=\"\">\r\n");
      out.write("                        <label for=\"password\">Password</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                 <!--로그인 버튼-->\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center mt-4\">\r\n");
      out.write("                    <div class=\"loginElements-Wrapper\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary\" id=\"btnLogin\">Login</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--카카오 로그인 버튼-->\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center mt-1\">\r\n");
      out.write("                    <div class=\"loginElements-Wrapper d-flex justify-content-center\" id=\"btnKakaoLogin-Wrapper\">\r\n");
      out.write("                        <img src=\"/resources/imgTmp/kakao_login_large_narrow.png\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--Join / Find ID / Find Password-->\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center mt-4 findWrapper\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toSignup.mem\">Sign up</a>\r\n");
      out.write("                    <span>&nbsp;|&nbsp;</span>\r\n");
      out.write("                    <a href=\"#\" onclick=\"modalCall()\">Find ID</a>\r\n");
      out.write("                    <span>&nbsp;|&nbsp;</span>\r\n");
      out.write("                    <a href=\"#\" onclick=\"modalCall2()\">Find Password</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 아이디 찾기 modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"findIdModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">아이디 찾기</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"Wrapper\">\r\n");
      out.write("                        <!--아이디 찾기 - 휴대전화-->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col\">\r\n");
      out.write("                                <div class=\"form-check\">\r\n");
      out.write("                                    <input class=\"form-check-input\" type=\"radio\" name=\"exampleRadios\"\r\n");
      out.write("                                        id=\"exampleRadios1\" value=\"option1\" checked>\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"exampleRadios1\">\r\n");
      out.write("                                        휴대전화로 찾기\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--아이디 찾기 - 휴대전화 입력-->\r\n");
      out.write("                        <div class=\"row\" id=\"findPhoneArea\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <p>회원정보에 등록된 휴대전화와 입력한 휴대전화 번호가 같아야, 인증번호를 받을 수 있습니다.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                                <label for=\"phone1\">휴대전화</label>\r\n");
      out.write("                                <select class=\"form-select\" aria-label=\"Default select example\" id=\"phone1\"\r\n");
      out.write("                                    name=\"phone1\" required>\r\n");
      out.write("                                    <option selected>010</option>\r\n");
      out.write("                                    <option value=\"1\">011</option>\r\n");
      out.write("                                    <option value=\"2\">016</option>\r\n");
      out.write("                                    <option value=\"2\">017</option>\r\n");
      out.write("                                    <option value=\"3\">018</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <span class=\"txtRegex\" id=\"txtRegex_phone\"></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-5 mb-3\">\r\n");
      out.write("                                <label for=\"phone2\">&nbsp;</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"phone2\" name=\"phone2\" maxlength=\"8\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                                <label for=\"btnSendPhone\">&nbsp;</label>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary clsBtn\" id=\"btnSendPhone\">인증번호\r\n");
      out.write("                                    받기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--아이디 찾기 - 휴대전화 인증번호 입력-->\r\n");
      out.write("                        <div class=\"row\" id=\"sendNum_Wrapper2\">\r\n");
      out.write("                            <div class=\"col-md-8 mb-3\">\r\n");
      out.write("                                <label for=\"inputNumber2\">인증번호</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"inputNumber2\" placeholder=\"인증번호 입력\"\r\n");
      out.write("                                    required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                                <label for=\"btnSubmit2\">&nbsp;</label>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary clsBtn\" id=\"btnSubmit2\">인증번호\r\n");
      out.write("                                    확인</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--아이디 찾기 - 경계선-->\r\n");
      out.write("                        <hr class=\"mb-4\">\r\n");
      out.write("                        <!--아이디 찾기 - 이메일-->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col\">\r\n");
      out.write("                                <div class=\"form-check\">\r\n");
      out.write("                                    <input class=\"form-check-input\" type=\"radio\" name=\"exampleRadios\"\r\n");
      out.write("                                        id=\"exampleRadios2\" value=\"option2\">\r\n");
      out.write("                                    <label class=\"form-check-label\" for=\"exampleRadios2\">\r\n");
      out.write("                                        이메일로 찾기\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--아이디 찾기 - 이메일 입력-->\r\n");
      out.write("                        <div class=\"row\" id=\"findEmailArea\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <p>회원정보에 등록된 이메일 주소와 입력한 이메일 주소가 같아야, 인증번호를 받을 수 있습니다.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-8 mb-3\">\r\n");
      out.write("                                <label for=\"email\">이메일</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" maxlength=\"35\"\r\n");
      out.write("                                    placeholder=\"이메일 입력\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                                <label for=\"emailCheck\">&nbsp;</label>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary clsBtn\" id=\"btnSendEmail\">인증번호\r\n");
      out.write("                                    받기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--아이디 찾기 - 이메일 인증번호 입력-->\r\n");
      out.write("                        <div class=\"row\" id=\"sendNum_Wrapper\">\r\n");
      out.write("                            <div class=\"col-md-8 mb-3\">\r\n");
      out.write("                                <label for=\"inputNumber\">인증번호</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"inputNumber\" placeholder=\"인증번호 입력\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                                <label for=\"btnSubmit\">&nbsp;</label>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary clsBtn\" id=\"btnSubmit\">인증번호 확인</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 비밀번호 찾기 modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"findPwModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"exampleModalLabel\">비밀번호 찾기</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <!--비밀번호 찾기 - 아이디 입력-->\r\n");
      out.write("                    <div class=\"pwFindWrapper\" id=\"firstWrap\">\r\n");
      out.write("                        <p>아이디를 입력해주세요.</p>\r\n");
      out.write("                        <div class=\"row my-4\">\r\n");
      out.write("                            <div class=\"col-md-12 mb-3 py-2\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"inputId\" name=\"user_id\"\r\n");
      out.write("                                    placeholder=\"PhotoFolio 아이디\" maxlength=\"9\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-12 mb-3 d-flex justify-content-center\">\r\n");
      out.write("                                <button class=\"btn btn-primary clsBtn\" type=\"button\" id=\"idCheck\">다음</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!--비밀번호 찾기 - 휴대전화-->\r\n");
      out.write("                    <div class=\"pwFindWrapper\" id=\"secondWrap\">\r\n");
      out.write("                        <div class=\"row\" id=\"radioArea2\">\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <p>회원정보에 등록된 이메일과 입력한 이메일이 같아야, 새 비밀번호를 받을 수 있습니다.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-8 mb-3\">\r\n");
      out.write("                                <label for=\"email2\">이메일</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"email2\" name=\"email\" maxlength=\"35\"\r\n");
      out.write("                                    placeholder=\"이메일 입력\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                                <label for=\"btnSendEmail2\">&nbsp;</label>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary clsBtn\" id=\"btnSendEmail2\">전송</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!--modal 호출 버튼-->\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary clsModal\" data-bs-toggle=\"modal\" data-bs-target=\"#findIdModal\"\r\n");
      out.write("        id=\"btnModalCall\">\r\n");
      out.write("    </button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary clsModal\" data-bs-toggle=\"modal\" data-bs-target=\"#findPwModal\"\r\n");
      out.write("        id=\"btnModalCall2\">\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        /*** 로그인 영역 ***/\r\n");
      out.write("\r\n");
      out.write("        // FindID으로 모달창 열기\r\n");
      out.write("        function modalCall() {\r\n");
      out.write("            document.getElementById(\"btnModalCall\").click();\r\n");
      out.write("        }\r\n");
      out.write("        // Find Password으로 모달창 열기\r\n");
      out.write("        function modalCall2() {\r\n");
      out.write("            document.getElementById(\"btnModalCall2\").click();\r\n");
      out.write("        }\r\n");
      out.write("        // 로그인 버튼 클릭시\r\n");
      out.write("        document.getElementById(\"btnLogin\").addEventListener(\"click\", function () {\r\n");
      out.write("            loginRequest();\r\n");
      out.write("        });\r\n");
      out.write("        // 카카오 로그인 클릭시\r\n");
      out.write("        document.getElementById(\"btnKakaoLogin-Wrapper\").addEventListener(\"click\", function() {\r\n");
      out.write("            location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toKakaoLogin.mem\";\r\n");
      out.write("        });\r\n");
      out.write("        // 입력창에서 enter키 입력시 로그인 요청\r\n");
      out.write("        const id = document.getElementById(\"id\");\r\n");
      out.write("        const password = document.getElementById(\"password\");\r\n");
      out.write("        id.addEventListener(\"keypress\", function (e) {\r\n");
      out.write("            if (e.keyCode == 13 && id.value !== \"\" && password.value !== \"\") {\r\n");
      out.write("                // id, pw 값 존재\r\n");
      out.write("                loginRequest();\r\n");
      out.write("            }\r\n");
      out.write("            if (e.keyCode == 13 && (id.value == \"\" || password.value == \"\")) {\r\n");
      out.write("                alert(\"ID or PW를 제대로 입력해주세요.\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        password.addEventListener(\"keypress\", function (e) {\r\n");
      out.write("            if (e.keyCode == 13 && id.value !== \"\" && password.value !== \"\") {\r\n");
      out.write("                // id, pw 값 존재\r\n");
      out.write("                loginRequest();\r\n");
      out.write("            }\r\n");
      out.write("            if (e.keyCode == 13 && (id.value == \"\" || password.value == \"\")) {\r\n");
      out.write("                alert(\"ID or PW를 제대로 입력해주세요.\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("     // 로그인 요청\r\n");
      out.write("        function loginRequest() {\r\n");
      out.write("            const data = $(\"#formLogin\").serialize();\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loginProc.mem\",\r\n");
      out.write("                data: data\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                if (data == \"true\") { // 로그인 성공 -> 메인 페이지로 이동\r\n");
      out.write("                    location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toHome.ho\";\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"ID 혹은 Password를 제대로 입력하세요.\");\r\n");
      out.write("                }\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /*** 아이디 찾기 modal ***/\r\n");
      out.write("\r\n");
      out.write("        // 라디오 버튼 스위칭\r\n");
      out.write("        document.addEventListener(\"click\", function (e) {\r\n");
      out.write("            if (e.target.id == \"exampleRadios1\") {\r\n");
      out.write("                document.getElementById(\"findPhoneArea\").style.display = \"flex\";\r\n");
      out.write("                document.getElementById(\"findEmailArea\").style.display = \"none\";\r\n");
      out.write("            } else if (e.target.id == \"exampleRadios2\") {\r\n");
      out.write("                document.getElementById(\"findPhoneArea\").style.display = \"none\";\r\n");
      out.write("                document.getElementById(\"findEmailArea\").style.display = \"flex\";\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        // 인증번호 받기 버튼 (아이디 찾기 - 휴대전화 인증)\r\n");
      out.write("        let user_id2 = \"\"; \r\n");
      out.write("        document.getElementById(\"btnSendPhone\").addEventListener(\"click\", function () {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findIdByPhoneProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    phone: document.getElementById(\"phone1\").value\r\n");
      out.write("                        + document.getElementById(\"phone2\").value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                if (data == \"false\") {\r\n");
      out.write("                    alert(\"존재하지 않는 휴대전화입니다.\");\r\n");
      out.write("                } else { \r\n");
      out.write("                    user_id2 = data;\r\n");
      out.write("                    alert(\"인증번호를 입력해주세요\");\r\n");
      out.write("                    document.getElementById(\"sendNum_Wrapper2\").style.display = \"flex\"; \r\n");
      out.write("                    sendNumberByPhone(); \r\n");
      out.write("                    document.getElementById(\"btnSendPhone\").disabled = \"disabled\";\r\n");
      out.write("                }\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        // 인증번호 발송 (아이디 찾기 - 휴대전화 인증)\r\n");
      out.write("        let verification_number2 = 0; \r\n");
      out.write("        function sendNumberByPhone() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sendSmsProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    phoneNumber: document.getElementById(\"phone1\").value\r\n");
      out.write("                        + document.getElementById(\"phone2\").value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                verification_number2 = data;\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        // 인증번호 확인 버튼 (아이디 찾기 - 휴대전화 인증)\r\n");
      out.write("        const inputNumber2 = document.getElementById(\"inputNumber2\"); \r\n");
      out.write("        document.getElementById(\"btnSubmit2\").addEventListener(\"click\", function () {\r\n");
      out.write("            if (inputNumber2.value == verification_number2) {\r\n");
      out.write("                alert(\"당신의 아이디는 \" + user_id2 + \" 입니다.\"); \r\n");
      out.write("                document.getElementById(\"inputNumber2\").readOnly = \"true\"; \r\n");
      out.write("                document.getElementById(\"btnSubmit2\").disabled = \"disabled\"; \r\n");
      out.write("                $('#findIdModal').modal('hide');\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"인증번호를 잘못 입력하셨습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        // 인증번호 받기 버튼  (아이디 찾기 - 이메일 인증)\r\n");
      out.write("        let user_id = \"\"; \r\n");
      out.write("        document.getElementById(\"btnSendEmail\").addEventListener(\"click\", function () {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findIdByEmailProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    email: document.getElementById(\"email\").value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                if (data == \"false\") {\r\n");
      out.write("                    alert(\"존재하지 않는 이메일입니다.\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    user_id = data;\r\n");
      out.write("                    alert(\"인증번호를 입력해주세요\");\r\n");
      out.write("                    document.getElementById(\"sendNum_Wrapper\").style.display = \"flex\"; \r\n");
      out.write("                    sendNumberByEmail(); \r\n");
      out.write("                    document.getElementById(\"btnSendEmail\").disabled = \"disabled\";\r\n");
      out.write("                }\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        // 인증번호 발송 (아이디 찾기 - 이메일 인증)\r\n");
      out.write("        let verification_number = 0; \r\n");
      out.write("        function sendNumberByEmail() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sendEmailProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    email: document.getElementById(\"email\").value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                verification_number = data;\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        // 인증번호 확인 버튼 (아이디 찾기 - 이메일 인증)\r\n");
      out.write("        const inputNumber = document.getElementById(\"inputNumber\"); \r\n");
      out.write("        document.getElementById(\"btnSubmit\").addEventListener(\"click\", function () {\r\n");
      out.write("            if (inputNumber.value == verification_number) {\r\n");
      out.write("                alert(\"당신의 아이디는 \" + user_id + \" 입니다.\"); \r\n");
      out.write("                document.getElementById(\"inputNumber\").readOnly = \"true\"; \r\n");
      out.write("                document.getElementById(\"btnSubmit\").disabled = \"disabled\"; \r\n");
      out.write("                $('#findIdModal').modal('hide');\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"인증번호를 잘못 입력하셨습니다.\");\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 아이디 입력 후, 다음 버튼 클릭시 \r\n");
      out.write("        let inputId = document.getElementById(\"inputId\");\r\n");
      out.write("        document.getElementById(\"idCheck\").addEventListener(\"click\", function () {\r\n");
      out.write("            $.ajax({ \r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/idCheckProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    id: inputId.value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                if (data == \"true\") { \r\n");
      out.write("                    document.getElementById(\"firstWrap\").style.display = \"none\";\r\n");
      out.write("                    document.getElementById(\"secondWrap\").style.display = \"inline-block\";\r\n");
      out.write("                } else if(data == \"kakao\") {\r\n");
      out.write("                    alert(\"카카오 회원은 해당 기능을 사용할 수 없습니다.\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"아이디를 제대로 입력하세요.\");\r\n");
      out.write("                }\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\".modal\").on(\"hidden.bs.modal\", function(){\r\n");
      out.write("            $(\"input\").val(\"\");\r\n");
      out.write("            document.getElementById(\"firstWrap\").style.display = \"block\";\r\n");
      out.write("            document.getElementById(\"secondWrap\").style.display = \"none\";\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 이메일로 패스워드 발급 \r\n");
      out.write("        document.getElementById(\"btnSendEmail2\").addEventListener(\"click\", function () {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/emailCheckProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    email: document.getElementById(\"email2\").value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                if (data == \"false\") {\r\n");
      out.write("                    alert(\"이메일을 정확히 입력해주세요\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    sendPasswordByEmail();\r\n");
      out.write("                }\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        // 임시 패스워드 발송\r\n");
      out.write("        function sendPasswordByEmail() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findPwByEmailProc.mem\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    id: inputId.value,\r\n");
      out.write("                    email: document.getElementById(\"email2\").value\r\n");
      out.write("                }\r\n");
      out.write("            }).done(function (data) {\r\n");
      out.write("                if (data == \"true\") {\r\n");
      out.write("                    alert(\"패스워드를 이메일로 발송했습니다.\");\r\n");
      out.write("                    $('#findPwModal').modal('hide');\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"패스워드 발송 실패.\");\r\n");
      out.write("                }\r\n");
      out.write("            }).fail(function (e) {\r\n");
      out.write("                console.log(e);\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
