/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-16 23:56:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.header;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1638513134000L));
    _jspx_dependants.put("jar:file:/D:/workspace_photofolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/photofolio/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Photofolio</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(" *{box-sizing: border-box;\r\n");
      out.write("            margin:0;}\r\n");
      out.write("       \r\n");
      out.write("       /*위로 올리는 버튼*/\r\n");
      out.write(".toUpBtn{\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("    right:0.625rem; /*10px*/\r\n");
      out.write("    bottom:0.625rem; /*10px*/\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    display: none;\r\n");
      out.write("} \r\n");
      out.write("        .Wrapper{\r\n");
      out.write("            border: 1px solid black;  \r\n");
      out.write("            margin: auto;\r\n");
      out.write("            width:118.75rem;/*1900px*/     \r\n");
      out.write("            overflow: hidden;                                                                                                          \r\n");
      out.write("        }\r\n");
      out.write("        .Header{\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 4.688rem; /*75px*/\r\n");
      out.write("            /* border-bottom:1px solid black; */\r\n");
      out.write("            background-color: rgb(86, 86, 196);\r\n");
      out.write("            width: 120rem;/*1900px*/\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("        /*로고, 검색창, 알림,프로필영역 나눔*/\r\n");
      out.write("        .Header>div{\r\n");
      out.write("            float: left; \r\n");
      out.write("        }\r\n");
      out.write("        /*로고 CSS*/\r\n");
      out.write("        #logoBox{\r\n");
      out.write("            width:20%;\r\n");
      out.write("            height: 100%; \r\n");
      out.write("        }\r\n");
      out.write("        #logoBox>p{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            color:white;\r\n");
      out.write("            font-size: xX-large;\r\n");
      out.write("            font-family: 'Jua', sans-serif;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-shadow: 6px 2px 2px gray;\r\n");
      out.write("            top:0.688rem; /*11px*/\r\n");
      out.write("            left:9.375rem; /*150px*/\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        /*검색창영역 CSS*/\r\n");
      out.write("        #inputBox{\r\n");
      out.write("            width:40%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            transform: translate(-100%, -50%);\r\n");
      out.write("            top:2.188rem; /*35px*/\r\n");
      out.write("            left:75rem; /*1200px*/\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper.active {}\r\n");
      out.write("        \r\n");
      out.write("        .search-wrapper .input-holder {    \r\n");
      out.write("            height: 4.375rem; /*70px*/\r\n");
      out.write("            width:4.375rem; /*70px*/\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            background: #5656c4;\r\n");
      out.write("            border-radius:6px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            transition: all 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper.active .input-holder {\r\n");
      out.write("            width:28.125rem; /*450px*/\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            transition: all .5s cubic-bezier(0.000, 0.105, 0.035, 1.570);\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .input-holder .search-input {\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height: 3.125rem; /*50px*/\r\n");
      out.write("            padding:0rem 4.375rem 0rem 1.25rem; /*0 70 0 20px*/\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top:0px;\r\n");
      out.write("            left:0px;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            border:none;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            font-family:\"Open Sans\", Arial, Verdana;\r\n");
      out.write("            font-size: 1rem; /*16px*/\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            line-height: 1.25rem; /*20px*/\r\n");
      out.write("            color: white;\r\n");
      out.write("            transform: translate(0, 60px); \r\n");
      out.write("            transition: all .3s cubic-bezier(0.000, 0.105, 0.035, 1.570);\r\n");
      out.write("            transition-delay: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper.active .input-holder .search-input {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translate(0, 10px); \r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .input-holder .search-icon {\r\n");
      out.write("            width:4.375rem; /*70px*/\r\n");
      out.write("            height:4.375rem; /*70px*/\r\n");
      out.write("            border:none;\r\n");
      out.write("            border-radius:6px;\r\n");
      out.write("            background: #5656c4;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            outline:none;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("            float:right;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper.active .input-holder .search-icon {\r\n");
      out.write("            width: 3.125rem; /*50px*/\r\n");
      out.write("            height:3.125rem; /*50px*/\r\n");
      out.write("            margin: 0.625rem; /*10px*/\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .input-holder .search-icon span {\r\n");
      out.write("            width:1.375rem; /*22px*/\r\n");
      out.write("            height:1.375rem; /*22px*/\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            transform: rotate(45deg);\r\n");
      out.write("            transition: all .4s cubic-bezier(0.650, -0.600, 0.240, 1.650);\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper.active .input-holder .search-icon span {\r\n");
      out.write("            transform: rotate(-45deg);\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .input-holder .search-icon span::before, .search-wrapper .input-holder .search-icon span::after {\r\n");
      out.write("            position: absolute; \r\n");
      out.write("            content:'';\r\n");
      out.write("        }\r\n");
      out.write("        /*돋보기 손잡이*/\r\n");
      out.write("        .search-wrapper .input-holder .search-icon span::before {\r\n");
      out.write("            width: 0.25rem; /*4px*/\r\n");
      out.write("            height: 1.25rem; /*20px*/\r\n");
      out.write("            left: 0.5rem; /*8px*/\r\n");
      out.write("            top: 1.188rem; /*19px*/\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            background: white;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .input-holder .search-icon span::after {\r\n");
      out.write("            width: 1.875rem; /*30px*/\r\n");
      out.write("            height: 1.875rem; /*30px*/\r\n");
      out.write("            left: -0.313rem; /*-5px*/\r\n");
      out.write("            top: -0.563rem; /*-9px*/\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            border: 4px solid white;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .close {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            top:1.5rem; /*24px*/\r\n");
      out.write("            right:1.25rem; /*20px*/\r\n");
      out.write("            width:1.563rem; /*25px*/\r\n");
      out.write("            height:1.563rem; /*25px*/\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transform: rotate(-180deg);\r\n");
      out.write("            transition: all .3s cubic-bezier(0.285, -0.450, 0.935, 0.110);\r\n");
      out.write("            transition-delay: 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper.active .close {\r\n");
      out.write("            right:-1.875rem; /*-30px*/\r\n");
      out.write("            transform: rotate(45deg);\r\n");
      out.write("            transition: all .6s cubic-bezier(0.000, 0.105, 0.035, 1.570);\r\n");
      out.write("            transition-delay: 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .close::before, .search-wrapper .close::after {\r\n");
      out.write("            position:absolute;\r\n");
      out.write("            content:'';\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .close::before {\r\n");
      out.write("            width: 0.313rem; /*5px*/\r\n");
      out.write("            height: 1.563rem; /*25px*/\r\n");
      out.write("            left: 0.625rem; /*10px*/\r\n");
      out.write("            top: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        .search-wrapper .close::after {\r\n");
      out.write("            width: 1.563rem; /*25px*/\r\n");
      out.write("            height: 0.313rem; /*5px*/\r\n");
      out.write("            left: 0px;\r\n");
      out.write("            top: 0.625rem; /*10px*/\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /*알림창영역*/\r\n");
      out.write("        #noticeBox{\r\n");
      out.write("            width: 10%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-top:0.938rem; /*15px*/\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        /*알림창 종 이미지 */\r\n");
      out.write("        #noticeBox>svg{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            left:81.875rem; /*1310px*/\r\n");
      out.write("        }\r\n");
      out.write("        /*알림창*/\r\n");
      out.write("        #noticeBox>div{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width:18.75rem; /*300px*/\r\n");
      out.write("            height: auto; /*300px*/\r\n");
      out.write("            top:4.688rem; /*75px*/\r\n");
      out.write("            left:73.938rem; /*1183*/\r\n");
      out.write("            display: none;\r\n");
      out.write("            background-color:#d9d9f2;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        /*업로드영역*/\r\n");
      out.write("        #uploadBox{\r\n");
      out.write("            width: 10%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /*업로드버튼 효과처리*/\r\n");
      out.write("        .uploadBtn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            border: none;\r\n");
      out.write("            background: rgba(86,86,196,1);\r\n");
      out.write("              background: linear-gradient(0deg, rgba(86,86,196,1) 0%, rgba(86,86,196,1) 100%);\r\n");
      out.write("              color: #fff;\r\n");
      out.write("              overflow: hidden;\r\n");
      out.write("              width:7.5rem; /*120px*/\r\n");
      out.write("              height: 2.5rem; /*40px*/\r\n");
      out.write("              top:1.125rem; /*18px*/\r\n");
      out.write("              left:89.188rem; /*1427px*/\r\n");
      out.write("          }\r\n");
      out.write("          /*업로드 아이콘*/\r\n");
      out.write("          .uploadBtn>svg{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left:0.625rem; /*10px*/\r\n");
      out.write("            top:0.125rem; /*2px*/\r\n");
      out.write("          }\r\n");
      out.write("          /*업로드 문구*/\r\n");
      out.write("          .uploadBtn>span{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left:3.75rem; /*60px*/\r\n");
      out.write("          }\r\n");
      out.write("          .uploadBtn:hover {\r\n");
      out.write("              text-decoration: none;\r\n");
      out.write("              color: #fff;\r\n");
      out.write("          }\r\n");
      out.write("          .uploadBtn:before {\r\n");
      out.write("              content: '';\r\n");
      out.write("              display: inline-block;\r\n");
      out.write("              top: -11.25rem; /*-180px*/\r\n");
      out.write("              left: 1.875rem; /*30px*/\r\n");
      out.write("              width: 1.875rem; /*30px*/\r\n");
      out.write("              height: 10%;\r\n");
      out.write("              background-color: #fff;\r\n");
      out.write("              animation: shiny-btn1 3s ease-in-out infinite;\r\n");
      out.write("          }\r\n");
      out.write("          .uploadBtn:hover{\r\n");
      out.write("            opacity: .7;\r\n");
      out.write("          }\r\n");
      out.write("          .uploadBtn:active{\r\n");
      out.write("            box-shadow:  4px 4px 6px 0 rgba(255,255,255,.3),\r\n");
      out.write("                        -4px -4px 6px 0 rgba(116, 125, 136, .2), \r\n");
      out.write("              inset -4px -4px 6px 0 rgba(255,255,255,.2),\r\n");
      out.write("              inset 4px 4px 6px 0 rgba(0, 0, 0, .2);\r\n");
      out.write("          }\r\n");
      out.write("          @-webkit-keyframes shiny-btn1 {\r\n");
      out.write("              0% { -webkit-transform: scale(0) rotate(45deg); opacity: 0; }\r\n");
      out.write("              80% { -webkit-transform: scale(0) rotate(45deg); opacity: 0.5; }\r\n");
      out.write("              81% { -webkit-transform: scale(4) rotate(45deg); opacity: 1; }\r\n");
      out.write("              100% { -webkit-transform: scale(50) rotate(45deg); opacity: 0; }\r\n");
      out.write("          }\r\n");
      out.write("        \r\n");
      out.write("        /*프로필영역*/\r\n");
      out.write("        #profileBox{\r\n");
      out.write("            width:20%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        #profilePhoto{ /*프로필사진*/\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 3.125rem; /*50px*/\r\n");
      out.write("            height: 3.125rem; /*50px*/\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            margin-top:0.625rem; /*10px*/\r\n");
      out.write("            left: 101.25rem; /*1620px*/\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            overflow:hidden;\r\n");
      out.write("        }\r\n");
      out.write("     	 #profilePhoto>img{\r\n");
      out.write("    		width: 100%;\r\n");
      out.write("   			height: 100%;\r\n");
      out.write("   		 	object-fit:cover;\r\n");
      out.write("        }\r\n");
      out.write("        /*프로필메뉴*/\r\n");
      out.write("        #profileMenu{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background-color: #5656c4;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width:12.5rem; /*200px*/\r\n");
      out.write("            height: 200px; /*200px*/\r\n");
      out.write("            top:4.688rem; /*75px*/\r\n");
      out.write("            left:96.875rem; /*1550px*/\r\n");
      out.write("            display:none;\r\n");
      out.write("        }\r\n");
      out.write("        #profileMenu>ul{ \r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding-left: 0;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        #profileMenu>ul>a>li{\r\n");
      out.write("            border: 1px solid white;\r\n");
      out.write("            height: 33%;\r\n");
      out.write("            padding-top: 0.938rem; /*15px*/\r\n");
      out.write("        }\r\n");
      out.write("        #profileMenu>ul>a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color:white;\r\n");
      out.write("            font-size: large;\r\n");
      out.write("        }\r\n");
      out.write("        /*프로필 메뉴 호버했을때의 효과*/\r\n");
      out.write("        #profileMenu>ul>a:hover{\r\n");
      out.write("            color:rgb(86, 86, 196);\r\n");
      out.write("        }\r\n");
      out.write("        #profileMenu>ul>a>li:hover {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("        /*로그인 영역*/\r\n");
      out.write("        #loginBox{\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /*로그인 버튼처리*/\r\n");
      out.write("        \r\n");
      out.write("        .loginBtn{/*버튼 움직일때는 이 값을 건드리기*/\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 100rem; /*1600px*/\r\n");
      out.write("            top:1.063rem; /*17px*/\r\n");
      out.write("            border:none;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            width: 8.125rem; /*130px*/\r\n");
      out.write("            height: 2.5rem; /*40px*/\r\n");
      out.write("            line-height: 2.625rem; /*42px*/\r\n");
      out.write("            -webkit-perspective: 230px;\r\n");
      out.write("            perspective: 230px;\r\n");
      out.write("          }\r\n");
      out.write("          .loginBtn span {\r\n");
      out.write("            background: rgb(166, 166, 221);\r\n");
      out.write("          background: linear-gradient(0deg, rgb(166, 166, 221) 0%, rgb(86, 86, 196) 100%);\r\n");
      out.write("            display: block;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 8.125rem; /*130px*/\r\n");
      out.write("            height: 2.5rem; /*40px*/\r\n");
      out.write("            box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),\r\n");
      out.write("             7px 7px 20px 0px rgba(0,0,0,.1),\r\n");
      out.write("             4px 4px 5px 0px rgba(0,0,0,.1);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin:0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            -webkit-box-sizing: border-box;\r\n");
      out.write("            -moz-box-sizing: border-box;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            -webkit-transition: all .3s;\r\n");
      out.write("            transition: all .3s;\r\n");
      out.write("            top:0;\r\n");
      out.write("            left:0;\r\n");
      out.write("            color:white;\r\n");
      out.write("          }\r\n");
      out.write("          .loginBtn span:nth-child(1) {\r\n");
      out.write("            box-shadow:\r\n");
      out.write("             -7px -7px 20px 0px #fff9,\r\n");
      out.write("             -4px -4px 5px 0px #fff9,\r\n");
      out.write("             7px 7px 20px 0px #0002,\r\n");
      out.write("             4px 4px 5px 0px #0001;\r\n");
      out.write("            -webkit-transform: rotateX(90deg);\r\n");
      out.write("            -moz-transform: rotateX(90deg);\r\n");
      out.write("            transform: rotateX(90deg);\r\n");
      out.write("            -webkit-transform-origin: 50% 50% -20px;\r\n");
      out.write("            -moz-transform-origin: 50% 50% -20px;\r\n");
      out.write("            transform-origin: 50% 50% -20px;\r\n");
      out.write("          }\r\n");
      out.write("          .loginBtn span:nth-child(2) {\r\n");
      out.write("            -webkit-transform: rotateX(0deg);\r\n");
      out.write("            -moz-transform: rotateX(0deg);\r\n");
      out.write("            transform: rotateX(0deg);\r\n");
      out.write("            -webkit-transform-origin: 50% 50% -20px;\r\n");
      out.write("            -moz-transform-origin: 50% 50% -20px;\r\n");
      out.write("            transform-origin: 50% 50% -20px;\r\n");
      out.write("          }\r\n");
      out.write("          .loginBtn:hover span:nth-child(1) {\r\n");
      out.write("            box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),\r\n");
      out.write("             7px 7px 20px 0px rgba(0,0,0,.1),\r\n");
      out.write("             4px 4px 5px 0px rgba(0,0,0,.1);\r\n");
      out.write("            -webkit-transform: rotateX(0deg);\r\n");
      out.write("            -moz-transform: rotateX(0deg);\r\n");
      out.write("            transform: rotateX(0deg);\r\n");
      out.write("          }\r\n");
      out.write("          .loginBtn:hover span:nth-child(2) {\r\n");
      out.write("            box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),\r\n");
      out.write("             7px 7px 20px 0px rgba(0,0,0,.1),\r\n");
      out.write("             4px 4px 5px 0px rgba(0,0,0,.1);\r\n");
      out.write("           color: transparent;\r\n");
      out.write("            -webkit-transform: rotateX(-90deg);\r\n");
      out.write("            -moz-transform: rotateX(-90deg);\r\n");
      out.write("            transform: rotateX(-90deg);\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          /*** notice영역 ***/\r\n");
      out.write("\r\n");
      out.write(".noti_table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".noti_table>tr>td{\r\n");
      out.write("	padding-right:10px;\r\n");
      out.write("}\r\n");
      out.write(".noti_userImg_wrapper {\r\n");
      out.write("    width: 70px;\r\n");
      out.write("}\r\n");
      out.write("#noti_userImg {\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    border-radius: 75%;\r\n");
      out.write("}\r\n");
      out.write(".noti_msg {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("}\r\n");
      out.write(".noti_msg > span {\r\n");
      out.write("    font-size: small;\r\n");
      out.write("}\r\n");
      out.write(".noti_delete {\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("}\r\n");
      out.write(".noti_delete > img {\r\n");
      out.write("    opacity: 70%;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".noti_date {\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    /* height: 25px; */\r\n");
      out.write("}\r\n");
      out.write(".noti_date > span {\r\n");
      out.write("    font-size: small;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <!--위로 올리는 버튼-->\r\n");
      out.write("    <div class=\"toUpBtn\">\r\n");
      out.write("        <svg xmlns=\"http://www.w3.org/2000/svg\" id=\"toUp\" width=\"35\" height=\"35\" fill=\"currentColor\" class=\"bi bi-arrow-up-circle-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M16 8A8 8 0 1 0 0 8a8 8 0 0 0 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z\"/>\r\n");
      out.write("          </svg>\r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"Header\">\r\n");
      out.write("            <!--로고 영역-->\r\n");
      out.write("            <div id=\"logoBox\">\r\n");
      out.write("                <p id=\"logo\">PhotoFolio</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--검색창 영역-->\r\n");
      out.write("            <div id=\"inputBox\">\r\n");
      out.write("                <div class=\"search-wrapper\">\r\n");
      out.write("                    <div class=\"input-holder\">\r\n");
      out.write("                        <input onkeyup=\"enterkey();\" type=\"text\" id=\"search-input\" class=\"search-input\" placeholder=\"찾으실 아이디, 제목, 내용을 입력해주세요.\" style=\"color: black;\" />\r\n");
      out.write("                        <!-- <input type=\"text\" class=\"search-input\" placeholder=\"Type to search\" style=\"color: black;\"/> -->\r\n");
      out.write("                        <button class=\"search-icon\" onclick=\"searchToggle(this, event);\"><span></span></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"close\" onclick=\"searchToggle(this, event);\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--알림창 버튼영역 (아이콘 클릭시 알림창 내려옴) + 비로그인시 숨김-->\r\n");
      out.write("				<div id=\"noticeBox\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("            <!--업로드 버튼영역 + 비로그인시 숨김-->\r\n");
      out.write("            \r\n");
      out.write("	            <div id=\"uploadBox\">\r\n");
      out.write("	            	");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("            	           	 \r\n");
      out.write("        </div>\r\n");
      out.write("    	\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.js\" integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("    <script>\r\n");
      out.write("        //일정길이 내려갔을때 위로 올리는 버튼 드러남\r\n");
      out.write("        $( window ).scroll( function() {\r\n");
      out.write("            if ( $( this ).scrollTop() > 200 ) {\r\n");
      out.write("                $( '.toUpBtn' ).fadeIn();\r\n");
      out.write("            } else {\r\n");
      out.write("                $('.toUpBtn').fadeOut();\r\n");
      out.write("            }\r\n");
      out.write("        } );\r\n");
      out.write("\r\n");
      out.write("        //클릭했을 때 스르륵 올라가는 애니메이션\r\n");
      out.write("        $( '.toUpBtn' ).click( function() {\r\n");
      out.write("            $( 'html, body' ).animate( { scrollTop : 0 }, 100 );\r\n");
      out.write("            return false;\r\n");
      out.write("        } );\r\n");
      out.write("        //검색창 열리고 닫히는 스크립트\r\n");
      out.write("        function searchToggle(obj, evt){\r\n");
      out.write("            var container = $(obj).closest('.search-wrapper');\r\n");
      out.write("                if(!container.hasClass('active')){\r\n");
      out.write("                    container.addClass('active');\r\n");
      out.write("                    evt.preventDefault(); \r\n");
      out.write("                }else if(container.find('.search-input').val()!=\"\"){\r\n");
      out.write("                	let inputVal = container.find('.search-input').val();\r\n");
      out.write("                	console.log(\"inputVal : 1 : \"+inputVal);\r\n");
      out.write("                	console.log(\"1 : \"+ container.find('.search-input').val());\r\n");
      out.write("                	console.log(\"눌림 눌림\");\r\n");
      out.write("                    location.href =\"/toSearchByIdOrNickname.bo?inputVal=\"+inputVal;\r\n");
      out.write("                }else if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){\r\n");
      out.write("                    container.removeClass('active');\r\n");
      out.write("                    // clear input\r\n");
      out.write("                    var inputVal = container.find('.search-input').val();\r\n");
      out.write("                    console.log(\"inputVal : \"+inputVal);\r\n");
      out.write("                    \r\n");
      out.write("                   /*  container.find('.search-input').val(''); */\r\n");
      out.write("                }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function enterkey(){\r\n");
      out.write("            if (window.event.keyCode == 13) {\r\n");
      out.write("               console.log($('#search-input').val());\r\n");
      out.write("               if($('#search-input').val()!=\"\"){\r\n");
      out.write("                    let inputVal = $('#search-input').val();\r\n");
      out.write("                     location.href =\"/toSearchByIdOrNickname.bo?inputVal=\"+inputVal;\r\n");
      out.write("                 }\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("			        /* function searchToggle(obj, evt){\r\n");
      out.write("			            var container = $(obj).closest('.search-wrapper');\r\n");
      out.write("			                if(!container.hasClass('active')){\r\n");
      out.write("			                    container.addClass('active');\r\n");
      out.write("			                    evt.preventDefault();\r\n");
      out.write("			                }\r\n");
      out.write("			                else if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){\r\n");
      out.write("			                    container.removeClass('active');\r\n");
      out.write("			                    // clear input\r\n");
      out.write("			                    container.find('.search-input').val('');\r\n");
      out.write("			                }\r\n");
      out.write("			        } */\r\n");
      out.write("			        //종버튼 클릭하면 알림창 나타나기/없어지기\r\n");
      out.write("			        $(\"#noticeImg\").click(function(){\r\n");
      out.write("			            let submenu = $(this).next(\"div\");\r\n");
      out.write("			            if(submenu.is(\":visible\")){\r\n");
      out.write("			                submenu.fadeOut();\r\n");
      out.write("			            }else{\r\n");
      out.write("			                submenu.fadeIn();\r\n");
      out.write("			            }\r\n");
      out.write("			        });\r\n");
      out.write("			        //로그인후 프로필 클릭하면 목록창이 나옴\r\n");
      out.write("			        $(\"#profilePhoto\").click(function(){\r\n");
      out.write("			            let submenu = $(this).next(\"div\");\r\n");
      out.write("			            if(submenu.is(\":visible\")){\r\n");
      out.write("			                submenu.fadeOut();\r\n");
      out.write("			            }else{\r\n");
      out.write("			                submenu.fadeIn();\r\n");
      out.write("			            }\r\n");
      out.write("			        });\r\n");
      out.write("			      //로고누르면 메인으로 \r\n");
      out.write("			        $(\"#logo\").click(function(){\r\n");
      out.write("			            location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"\r\n");
      out.write("			        })\r\n");
      out.write("			        //My Infomation 누르면 개인정보페이지로 이동\r\n");
      out.write("			        $(\"#btnMyInfo\").click(function(){\r\n");
      out.write("			            location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toMyPage.mem\"\r\n");
      out.write("			        })\r\n");
      out.write("			        //로그인 버튼 누르면 로그인창 뜨도록\r\n");
      out.write("			        $(\".loginBtn\").click(function(){\r\n");
      out.write("			        	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toLogin.mem\"\r\n");
      out.write("			        })\r\n");
      out.write("			        $(\".uploadBtn\").click(function(){\r\n");
      out.write("			        	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/toInsertPost.bo\"\r\n");
      out.write("			        })\r\n");
      out.write("			        \r\n");
      out.write("			        $(document).ready(function() {\r\n");
      out.write("			    getNoti(); // 로드되면 1회 실행\r\n");
      out.write("			    setInterval(getNoti, 3000); // 3초마다 재실행\r\n");
      out.write("			    getProfile();\r\n");
      out.write("			});\r\n");
      out.write("			      \r\n");
      out.write("			   let notiShare = \"\";\r\n");
      out.write("			\r\n");
      out.write("			function getNoti() {\r\n");
      out.write("			    $.ajax({\r\n");
      out.write("			        type: \"get\",\r\n");
      out.write("			        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/selectNotiProc.bo\",\r\n");
      out.write("			        dataType: \"json\"\r\n");
      out.write("			    }).done(function(rs) {\r\n");
      out.write("			        if(!(rs == \"fail\")) {\r\n");
      out.write("			        	 $(\".noti_table\").empty(); // 기존 리스트 제거\r\n");
      out.write("			            for (let noti of rs) {\r\n");
      out.write("	                     	let notiList = '<tr>'\r\n");
      out.write("	                            + '<td class=\"noti_userImg_wrapper\">'\r\n");
      out.write("	                            + '<img id=\"noti_userImg\" src=\"' + noti.profilephoto_path + '\">'\r\n");
      out.write("	                            + '</td>'\r\n");
      out.write("	                            + '<td class=\"noti_msg\">'\r\n");
      out.write("	                            + '<span>' + noti.notiDto.noti_msg + '</span><br>'\r\n");
      out.write("	                            + '<span>' + noti.notiDto.noti_date + '</span>'\r\n");
      out.write("	                            + '</td>'\r\n");
      out.write("	                            + '<td class=\"noti_delete\">'\r\n");
      out.write("	                            + '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgTmp/trash.svg\" id=\"' + noti.notiDto.noti_no + '\">'\r\n");
      out.write("	                            + '</td>'\r\n");
      out.write("	                            + '</tr>';\r\n");
      out.write("	                        notiShare = notiList; \r\n");
      out.write("	                        $(\".noti_table\").append(notiList); \r\n");
      out.write("			                \r\n");
      out.write("			            }\r\n");
      out.write("			        } else {\r\n");
      out.write("			            console.log(\"수신 실패\");\r\n");
      out.write("			        }\r\n");
      out.write("			    }).fail(function(e) {\r\n");
      out.write("			        console.log(e);\r\n");
      out.write("			    });\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 알림 삭제\r\n");
      out.write("			$(document).on(\"click\", \".noti_delete > img\", function(e) { // 바인딩 처리\r\n");
      out.write("			    $.ajax({\r\n");
      out.write("			        type: \"post\",\r\n");
      out.write("			        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteNotiProc.bo\",\r\n");
      out.write("			        data: {\r\n");
      out.write("			            noti_no: e.target.id\r\n");
      out.write("			        }\r\n");
      out.write("			    }).done(function(rs){\r\n");
      out.write("			        console.log(rs);\r\n");
      out.write("			        if(rs == \"true\") {\r\n");
      out.write("			            $(e.target).parents(\"tr\").remove();\r\n");
      out.write("			        }\r\n");
      out.write("			    }).fail(function(e){\r\n");
      out.write("			        console.log(e);\r\n");
      out.write("			    });\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//프로필 ajax로 출력\r\n");
      out.write("			function getProfile() {\r\n");
      out.write("			    $.ajax({\r\n");
      out.write("			        type: \"get\",\r\n");
      out.write("			        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/selectPhoto.mem\",\r\n");
      out.write("			        dataType: \"json\"\r\n");
      out.write("			    }).done(function(rs) {\r\n");
      out.write("			        if(!(rs == \"fail\")) {\r\n");
      out.write("			        	 let photo = rs\r\n");
      out.write("			        	 console.log(photo);\r\n");
      out.write("			            \r\n");
      out.write("	                     	let profilePhoto = '<img src=\"' + photo + '\">'\r\n");
      out.write("	                        \r\n");
      out.write("	                        $(\"#profilePhoto\").append(profilePhoto); \r\n");
      out.write("			                \r\n");
      out.write("			            \r\n");
      out.write("			        } else {\r\n");
      out.write("			            console.log(\"수신 실패\");\r\n");
      out.write("			        }\r\n");
      out.write("			    }).fail(function(e) {\r\n");
      out.write("			        console.log(e);\r\n");
      out.write("			    });\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /resources/header/header.jsp(488,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginSession}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				      <svg xmlns=\"http://www.w3.org/2000/svg\" id=\"noticeImg\" width=\"45\" height=\"45\" fill=\"currentColor\" class=\"bi bi-bell\" viewBox=\"0 0 16 16\">\r\n");
          out.write("				          <path d=\"M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z\"/>\r\n");
          out.write("				      </svg> \r\n");
          out.write("				      <div id=\"notice\">\r\n");
          out.write("				      		<table class=\"noti_table\">\r\n");
          out.write("				      		</table>\r\n");
          out.write("				            <!--동적 추가-->\r\n");
          out.write("				        </div>\r\n");
          out.write("				    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /resources/header/header.jsp(502,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginSession}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	                <button class=\"custom-btn uploadBtn\">\r\n");
          out.write("	                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"35\" height=\"35\" fill=\"currentColor\" class=\"bi bi-upload\" viewBox=\"0 0 16 16\">\r\n");
          out.write("	                        <path d=\"M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z\"/>\r\n");
          out.write("	                        <path d=\"M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z\"/>\r\n");
          out.write("	                      </svg>\r\n");
          out.write("	                    <span>Upload</span>\r\n");
          out.write("	                    <div class=\"dot\">\r\n");
          out.write("	                    </div>\r\n");
          out.write("	                </button>\r\n");
          out.write("	                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("     \r\n");
          out.write("	            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /resources/header/header.jsp(517,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginSession}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            <!--로그인 후의 프로필영역(프로필클릭시 메뉴단 내려옴)-->\r\n");
          out.write("			        <div id=\"profileBox\">\r\n");
          out.write("			            <div id=\"profilePhoto\">\r\n");
          out.write("			           		 <!-- ajax로 사진받아옴 -->\r\n");
          out.write("			            </div>\r\n");
          out.write("			            <div id=profileMenu>\r\n");
          out.write("			                <ul>\r\n");
          out.write("			                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/toUserPage.bo?currentPage=1\"><li>My Page</li></a>\r\n");
          out.write("			                    <a href=\"#\" id=\"btnMyInfo\"><li>My Infomation</li></a>\r\n");
          out.write("			                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logoutProc.mem\"><li>Log Out</li></a>\r\n");
          out.write("			                </ul>\r\n");
          out.write("			            </div>\r\n");
          out.write("			        </div>\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            	 <!--로그인 전의 로그인버튼영역-->\r\n");
          out.write("	            	<div id=\"loginBox\">\r\n");
          out.write("	                	<button type=\"button\" class=\"custom-btn loginBtn\"><span>Click!</span><span>Log In</span>\r\n");
          out.write("	                	</button>\r\n");
          out.write("	           		</div>\r\n");
          out.write("	            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
